// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/transaction/transaction_service.proto

package transactionv1

import (
	common "github.com/visvesh-ramesh/corebank/v1/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId  int64                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId    int64                  `protobuf:"varint,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	AmountMinor    int64                  `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_service_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *TransferRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *TransferRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *TransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransferRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_service_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type DepositRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ToAccountId    int64                  `protobuf:"varint,1,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	AmountMinor    int64                  `protobuf:"varint,2,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// External reference (card auth ID, NEFT UTR, etc.).
	SourceReference string `protobuf:"bytes,5,opt,name=source_reference,json=sourceReference,proto3" json:"source_reference,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_service_proto_rawDescGZIP(), []int{2}
}

func (x *DepositRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *DepositRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *DepositRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DepositRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *DepositRequest) GetSourceReference() string {
	if x != nil {
		return x.SourceReference
	}
	return ""
}

type DepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResponse) Reset() {
	*x = DepositResponse{}
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResponse) ProtoMessage() {}

func (x *DepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResponse.ProtoReflect.Descriptor instead.
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_service_proto_rawDescGZIP(), []int{3}
}

func (x *DepositResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type WithdrawRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId        int64                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	AmountMinor          int64                  `protobuf:"varint,2,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency             string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	IdempotencyKey       string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	DestinationReference string                 `protobuf:"bytes,5,opt,name=destination_reference,json=destinationReference,proto3" json:"destination_reference,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_service_proto_rawDescGZIP(), []int{4}
}

func (x *WithdrawRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *WithdrawRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *WithdrawRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WithdrawRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *WithdrawRequest) GetDestinationReference() string {
	if x != nil {
		return x.DestinationReference
	}
	return ""
}

type WithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawResponse) Reset() {
	*x = WithdrawResponse{}
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponse) ProtoMessage() {}

func (x *WithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResponse.ProtoReflect.Descriptor instead.
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_service_proto_rawDescGZIP(), []int{5}
}

func (x *WithdrawResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ListAccountTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Page          *common.PageRequest    `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountTransactionsRequest) Reset() {
	*x = ListAccountTransactionsRequest{}
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountTransactionsRequest) ProtoMessage() {}

func (x *ListAccountTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListAccountTransactionsRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ListAccountTransactionsRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAccountTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountTransactionsResponse) Reset() {
	*x = ListAccountTransactionsResponse{}
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountTransactionsResponse) ProtoMessage() {}

func (x *ListAccountTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListAccountTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListAccountTransactionsResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_v1_transaction_transaction_service_proto protoreflect.FileDescriptor

const file_v1_transaction_transaction_service_proto_rawDesc = "" +
	"\n" +
	"(v1/transaction/transaction_service.proto\x12\x0etransaction.v1\x1a\x1cgoogle/api/annotations.proto\x1a v1/transaction/transaction.proto\x1a\x16v1/common/common.proto\"\xe7\x01\n" +
	"\x0fTransferRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x02 \x01(\x03R\vtoAccountId\x12!\n" +
	"\famount_minor\x18\x03 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"Q\n" +
	"\x10TransferResponse\x12=\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.transaction.v1.TransactionR\vtransaction\"\xc7\x01\n" +
	"\x0eDepositRequest\x12\"\n" +
	"\rto_account_id\x18\x01 \x01(\x03R\vtoAccountId\x12!\n" +
	"\famount_minor\x18\x02 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12)\n" +
	"\x10source_reference\x18\x05 \x01(\tR\x0fsourceReference\"P\n" +
	"\x0fDepositResponse\x12=\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.transaction.v1.TransactionR\vtransaction\"\xd6\x01\n" +
	"\x0fWithdrawRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x03R\rfromAccountId\x12!\n" +
	"\famount_minor\x18\x02 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x123\n" +
	"\x15destination_reference\x18\x05 \x01(\tR\x14destinationReference\"Q\n" +
	"\x10WithdrawResponse\x12=\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.transaction.v1.TransactionR\vtransaction\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"W\n" +
	"\x16GetTransactionResponse\x12=\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.transaction.v1.TransactionR\vtransaction\"k\n" +
	"\x1eListAccountTransactionsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.common.v1.PageRequestR\x04page\"\x8f\x01\n" +
	"\x1fListAccountTransactionsResponse\x12?\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1b.transaction.v1.TransactionR\ftransactions\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page2\x9c\x05\n" +
	"\x12TransactionService\x12s\n" +
	"\bTransfer\x12\x1f.transaction.v1.TransferRequest\x1a .transaction.v1.TransferResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/transactions/transfer\x12o\n" +
	"\aDeposit\x12\x1e.transaction.v1.DepositRequest\x1a\x1f.transaction.v1.DepositResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/transactions/deposit\x12s\n" +
	"\bWithdraw\x12\x1f.transaction.v1.WithdrawRequest\x1a .transaction.v1.WithdrawResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/transactions/withdraw\x12~\n" +
	"\x0eGetTransaction\x12%.transaction.v1.GetTransactionRequest\x1a&.transaction.v1.GetTransactionResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/transactions/{id}\x12\xaa\x01\n" +
	"\x17ListAccountTransactions\x12..transaction.v1.ListAccountTransactionsRequest\x1a/.transaction.v1.ListAccountTransactionsResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/accounts/{account_id}/transactionsBAZ?github.com/visvesh-ramesh/corebank/v1/transaction;transactionv1b\x06proto3"

var (
	file_v1_transaction_transaction_service_proto_rawDescOnce sync.Once
	file_v1_transaction_transaction_service_proto_rawDescData []byte
)

func file_v1_transaction_transaction_service_proto_rawDescGZIP() []byte {
	file_v1_transaction_transaction_service_proto_rawDescOnce.Do(func() {
		file_v1_transaction_transaction_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_transaction_transaction_service_proto_rawDesc), len(file_v1_transaction_transaction_service_proto_rawDesc)))
	})
	return file_v1_transaction_transaction_service_proto_rawDescData
}

var file_v1_transaction_transaction_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_transaction_transaction_service_proto_goTypes = []any{
	(*TransferRequest)(nil),                 // 0: transaction.v1.TransferRequest
	(*TransferResponse)(nil),                // 1: transaction.v1.TransferResponse
	(*DepositRequest)(nil),                  // 2: transaction.v1.DepositRequest
	(*DepositResponse)(nil),                 // 3: transaction.v1.DepositResponse
	(*WithdrawRequest)(nil),                 // 4: transaction.v1.WithdrawRequest
	(*WithdrawResponse)(nil),                // 5: transaction.v1.WithdrawResponse
	(*GetTransactionRequest)(nil),           // 6: transaction.v1.GetTransactionRequest
	(*GetTransactionResponse)(nil),          // 7: transaction.v1.GetTransactionResponse
	(*ListAccountTransactionsRequest)(nil),  // 8: transaction.v1.ListAccountTransactionsRequest
	(*ListAccountTransactionsResponse)(nil), // 9: transaction.v1.ListAccountTransactionsResponse
	(*Transaction)(nil),                     // 10: transaction.v1.Transaction
	(*common.PageRequest)(nil),              // 11: common.v1.PageRequest
	(*common.PageResponse)(nil),             // 12: common.v1.PageResponse
}
var file_v1_transaction_transaction_service_proto_depIdxs = []int32{
	10, // 0: transaction.v1.TransferResponse.transaction:type_name -> transaction.v1.Transaction
	10, // 1: transaction.v1.DepositResponse.transaction:type_name -> transaction.v1.Transaction
	10, // 2: transaction.v1.WithdrawResponse.transaction:type_name -> transaction.v1.Transaction
	10, // 3: transaction.v1.GetTransactionResponse.transaction:type_name -> transaction.v1.Transaction
	11, // 4: transaction.v1.ListAccountTransactionsRequest.page:type_name -> common.v1.PageRequest
	10, // 5: transaction.v1.ListAccountTransactionsResponse.transactions:type_name -> transaction.v1.Transaction
	12, // 6: transaction.v1.ListAccountTransactionsResponse.page:type_name -> common.v1.PageResponse
	0,  // 7: transaction.v1.TransactionService.Transfer:input_type -> transaction.v1.TransferRequest
	2,  // 8: transaction.v1.TransactionService.Deposit:input_type -> transaction.v1.DepositRequest
	4,  // 9: transaction.v1.TransactionService.Withdraw:input_type -> transaction.v1.WithdrawRequest
	6,  // 10: transaction.v1.TransactionService.GetTransaction:input_type -> transaction.v1.GetTransactionRequest
	8,  // 11: transaction.v1.TransactionService.ListAccountTransactions:input_type -> transaction.v1.ListAccountTransactionsRequest
	1,  // 12: transaction.v1.TransactionService.Transfer:output_type -> transaction.v1.TransferResponse
	3,  // 13: transaction.v1.TransactionService.Deposit:output_type -> transaction.v1.DepositResponse
	5,  // 14: transaction.v1.TransactionService.Withdraw:output_type -> transaction.v1.WithdrawResponse
	7,  // 15: transaction.v1.TransactionService.GetTransaction:output_type -> transaction.v1.GetTransactionResponse
	9,  // 16: transaction.v1.TransactionService.ListAccountTransactions:output_type -> transaction.v1.ListAccountTransactionsResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v1_transaction_transaction_service_proto_init() }
func file_v1_transaction_transaction_service_proto_init() {
	if File_v1_transaction_transaction_service_proto != nil {
		return
	}
	file_v1_transaction_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_transaction_transaction_service_proto_rawDesc), len(file_v1_transaction_transaction_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_transaction_transaction_service_proto_goTypes,
		DependencyIndexes: file_v1_transaction_transaction_service_proto_depIdxs,
		MessageInfos:      file_v1_transaction_transaction_service_proto_msgTypes,
	}.Build()
	File_v1_transaction_transaction_service_proto = out.File
	file_v1_transaction_transaction_service_proto_goTypes = nil
	file_v1_transaction_transaction_service_proto_depIdxs = nil
}
