// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/transaction/transaction.proto

package transactionv1

import (
	common "github.com/visvesh-ramesh/corebank/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction is the customer-facing orchestration record of a money operation.
// It references the underlying ledger transaction once posted. The authoritative
// money movement lives in the Ledger; this is the saga coordination record.
//
// from_account_id and to_account_id are optional because:
//
//	DEPOSIT has no from_account (external source)
//	WITHDRAWAL has no to_account (external destination)
//
// ledger_transaction_id is optional until the ledger step completes.
type Transaction struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind           common.TransactionKind  `protobuf:"varint,2,opt,name=kind,proto3,enum=common.v1.TransactionKind" json:"kind,omitempty"`
	State          common.TransactionState `protobuf:"varint,3,opt,name=state,proto3,enum=common.v1.TransactionState" json:"state,omitempty"`
	FromAccountId  *int64                  `protobuf:"varint,4,opt,name=from_account_id,json=fromAccountId,proto3,oneof" json:"from_account_id,omitempty"` // empty for DEPOSIT
	ToAccountId    *int64                  `protobuf:"varint,5,opt,name=to_account_id,json=toAccountId,proto3,oneof" json:"to_account_id,omitempty"`       // empty for WITHDRAWAL
	Amount         *common.Money           `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey string                  `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Set once the Ledger has successfully posted the transaction.
	LedgerTransactionId *int64 `protobuf:"varint,8,opt,name=ledger_transaction_id,json=ledgerTransactionId,proto3,oneof" json:"ledger_transaction_id,omitempty"`
	// Populated when state == FAILED; describes why the saga was not completed.
	FailureReason string                 `protobuf:"bytes,9,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_v1_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_v1_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetKind() common.TransactionKind {
	if x != nil {
		return x.Kind
	}
	return common.TransactionKind(0)
}

func (x *Transaction) GetState() common.TransactionState {
	if x != nil {
		return x.State
	}
	return common.TransactionState(0)
}

func (x *Transaction) GetFromAccountId() int64 {
	if x != nil && x.FromAccountId != nil {
		return *x.FromAccountId
	}
	return 0
}

func (x *Transaction) GetToAccountId() int64 {
	if x != nil && x.ToAccountId != nil {
		return *x.ToAccountId
	}
	return 0
}

func (x *Transaction) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transaction) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Transaction) GetLedgerTransactionId() int64 {
	if x != nil && x.LedgerTransactionId != nil {
		return *x.LedgerTransactionId
	}
	return 0
}

func (x *Transaction) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_v1_transaction_transaction_proto protoreflect.FileDescriptor

const file_v1_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	" v1/transaction/transaction.proto\x12\x0etransaction.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16v1/common/common.proto\x1a\x15v1/common/enums.proto\"\xc3\x04\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1a.common.v1.TransactionKindR\x04kind\x121\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1b.common.v1.TransactionStateR\x05state\x12+\n" +
	"\x0ffrom_account_id\x18\x04 \x01(\x03H\x00R\rfromAccountId\x88\x01\x01\x12'\n" +
	"\rto_account_id\x18\x05 \x01(\x03H\x01R\vtoAccountId\x88\x01\x01\x12(\n" +
	"\x06amount\x18\x06 \x01(\v2\x10.common.v1.MoneyR\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x127\n" +
	"\x15ledger_transaction_id\x18\b \x01(\x03H\x02R\x13ledgerTransactionId\x88\x01\x01\x12%\n" +
	"\x0efailure_reason\x18\t \x01(\tR\rfailureReason\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAtB\x12\n" +
	"\x10_from_account_idB\x10\n" +
	"\x0e_to_account_idB\x18\n" +
	"\x16_ledger_transaction_idBAZ?github.com/visvesh-ramesh/corebank/v1/transaction;transactionv1b\x06proto3"

var (
	file_v1_transaction_transaction_proto_rawDescOnce sync.Once
	file_v1_transaction_transaction_proto_rawDescData []byte
)

func file_v1_transaction_transaction_proto_rawDescGZIP() []byte {
	file_v1_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_v1_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_transaction_transaction_proto_rawDesc), len(file_v1_transaction_transaction_proto_rawDesc)))
	})
	return file_v1_transaction_transaction_proto_rawDescData
}

var file_v1_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_transaction_transaction_proto_goTypes = []any{
	(*Transaction)(nil),           // 0: transaction.v1.Transaction
	(common.TransactionKind)(0),   // 1: common.v1.TransactionKind
	(common.TransactionState)(0),  // 2: common.v1.TransactionState
	(*common.Money)(nil),          // 3: common.v1.Money
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_v1_transaction_transaction_proto_depIdxs = []int32{
	1, // 0: transaction.v1.Transaction.kind:type_name -> common.v1.TransactionKind
	2, // 1: transaction.v1.Transaction.state:type_name -> common.v1.TransactionState
	3, // 2: transaction.v1.Transaction.amount:type_name -> common.v1.Money
	4, // 3: transaction.v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	4, // 4: transaction.v1.Transaction.completed_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_transaction_transaction_proto_init() }
func file_v1_transaction_transaction_proto_init() {
	if File_v1_transaction_transaction_proto != nil {
		return
	}
	file_v1_transaction_transaction_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_transaction_transaction_proto_rawDesc), len(file_v1_transaction_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_v1_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_v1_transaction_transaction_proto_msgTypes,
	}.Build()
	File_v1_transaction_transaction_proto = out.File
	file_v1_transaction_transaction_proto_goTypes = nil
	file_v1_transaction_transaction_proto_depIdxs = nil
}
