// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/transaction/transaction_service.proto

package transactionv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTransactionServiceDeposit = "/transaction.v1.TransactionService/Deposit"
const OperationTransactionServiceGetTransaction = "/transaction.v1.TransactionService/GetTransaction"
const OperationTransactionServiceListAccountTransactions = "/transaction.v1.TransactionService/ListAccountTransactions"
const OperationTransactionServiceTransfer = "/transaction.v1.TransactionService/Transfer"
const OperationTransactionServiceWithdraw = "/transaction.v1.TransactionService/Withdraw"

type TransactionServiceHTTPServer interface {
	// Deposit Deposit credits an account from an external source (e.g. card top-up).
	// The ledger entry credits the account and debits a system clearing account
	// so the transaction remains balanced.
	Deposit(context.Context, *DepositRequest) (*DepositResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	// ListAccountTransactions ListAccountTransactions returns the transaction history for one account.
	ListAccountTransactions(context.Context, *ListAccountTransactionsRequest) (*ListAccountTransactionsResponse, error)
	// Transfer Transfer moves money between two internal accounts.
	// Orchestration:
	//   1. validate both accounts exist and are ACTIVE (Account service)
	//   2. post a balanced debit/credit to the Ledger
	//   3. ledger success → COMPLETED; failure → FAILED (nothing moved)
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	// Withdraw Withdraw debits an account to an external destination.
	Withdraw(context.Context, *WithdrawRequest) (*WithdrawResponse, error)
}

func RegisterTransactionServiceHTTPServer(s *http.Server, srv TransactionServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/transactions/transfer", _TransactionService_Transfer0_HTTP_Handler(srv))
	r.POST("/v1/transactions/deposit", _TransactionService_Deposit0_HTTP_Handler(srv))
	r.POST("/v1/transactions/withdraw", _TransactionService_Withdraw0_HTTP_Handler(srv))
	r.GET("/v1/transactions/{id}", _TransactionService_GetTransaction0_HTTP_Handler(srv))
	r.GET("/v1/accounts/{account_id}/transactions", _TransactionService_ListAccountTransactions0_HTTP_Handler(srv))
}

func _TransactionService_Transfer0_HTTP_Handler(srv TransactionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TransferRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionServiceTransfer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Transfer(ctx, req.(*TransferRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TransferResponse)
		return ctx.Result(200, reply)
	}
}

func _TransactionService_Deposit0_HTTP_Handler(srv TransactionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DepositRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionServiceDeposit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Deposit(ctx, req.(*DepositRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DepositResponse)
		return ctx.Result(200, reply)
	}
}

func _TransactionService_Withdraw0_HTTP_Handler(srv TransactionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WithdrawRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionServiceWithdraw)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Withdraw(ctx, req.(*WithdrawRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WithdrawResponse)
		return ctx.Result(200, reply)
	}
}

func _TransactionService_GetTransaction0_HTTP_Handler(srv TransactionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTransactionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionServiceGetTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTransaction(ctx, req.(*GetTransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTransactionResponse)
		return ctx.Result(200, reply)
	}
}

func _TransactionService_ListAccountTransactions0_HTTP_Handler(srv TransactionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAccountTransactionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionServiceListAccountTransactions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAccountTransactions(ctx, req.(*ListAccountTransactionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAccountTransactionsResponse)
		return ctx.Result(200, reply)
	}
}

type TransactionServiceHTTPClient interface {
	// Deposit Deposit credits an account from an external source (e.g. card top-up).
	// The ledger entry credits the account and debits a system clearing account
	// so the transaction remains balanced.
	Deposit(ctx context.Context, req *DepositRequest, opts ...http.CallOption) (rsp *DepositResponse, err error)
	GetTransaction(ctx context.Context, req *GetTransactionRequest, opts ...http.CallOption) (rsp *GetTransactionResponse, err error)
	// ListAccountTransactions ListAccountTransactions returns the transaction history for one account.
	ListAccountTransactions(ctx context.Context, req *ListAccountTransactionsRequest, opts ...http.CallOption) (rsp *ListAccountTransactionsResponse, err error)
	// Transfer Transfer moves money between two internal accounts.
	// Orchestration:
	//   1. validate both accounts exist and are ACTIVE (Account service)
	//   2. post a balanced debit/credit to the Ledger
	//   3. ledger success → COMPLETED; failure → FAILED (nothing moved)
	Transfer(ctx context.Context, req *TransferRequest, opts ...http.CallOption) (rsp *TransferResponse, err error)
	// Withdraw Withdraw debits an account to an external destination.
	Withdraw(ctx context.Context, req *WithdrawRequest, opts ...http.CallOption) (rsp *WithdrawResponse, err error)
}

type TransactionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTransactionServiceHTTPClient(client *http.Client) TransactionServiceHTTPClient {
	return &TransactionServiceHTTPClientImpl{client}
}

// Deposit Deposit credits an account from an external source (e.g. card top-up).
// The ledger entry credits the account and debits a system clearing account
// so the transaction remains balanced.
func (c *TransactionServiceHTTPClientImpl) Deposit(ctx context.Context, in *DepositRequest, opts ...http.CallOption) (*DepositResponse, error) {
	var out DepositResponse
	pattern := "/v1/transactions/deposit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTransactionServiceDeposit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TransactionServiceHTTPClientImpl) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...http.CallOption) (*GetTransactionResponse, error) {
	var out GetTransactionResponse
	pattern := "/v1/transactions/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionServiceGetTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAccountTransactions ListAccountTransactions returns the transaction history for one account.
func (c *TransactionServiceHTTPClientImpl) ListAccountTransactions(ctx context.Context, in *ListAccountTransactionsRequest, opts ...http.CallOption) (*ListAccountTransactionsResponse, error) {
	var out ListAccountTransactionsResponse
	pattern := "/v1/accounts/{account_id}/transactions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionServiceListAccountTransactions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Transfer Transfer moves money between two internal accounts.
// Orchestration:
//   1. validate both accounts exist and are ACTIVE (Account service)
//   2. post a balanced debit/credit to the Ledger
//   3. ledger success → COMPLETED; failure → FAILED (nothing moved)
func (c *TransactionServiceHTTPClientImpl) Transfer(ctx context.Context, in *TransferRequest, opts ...http.CallOption) (*TransferResponse, error) {
	var out TransferResponse
	pattern := "/v1/transactions/transfer"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTransactionServiceTransfer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Withdraw Withdraw debits an account to an external destination.
func (c *TransactionServiceHTTPClientImpl) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...http.CallOption) (*WithdrawResponse, error) {
	var out WithdrawResponse
	pattern := "/v1/transactions/withdraw"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTransactionServiceWithdraw))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
