// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBusinessCustomer = "business_customers"

// BusinessCustomer mapped from table <business_customers>
type BusinessCustomer struct {
	ID                 int64   `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	CompanyName        string  `gorm:"column:company_name;type:character varying(255);not null" json:"company_name"`
	RegistrationNumber *string `gorm:"column:registration_number;type:character varying(100)" json:"registration_number"`
	TaxID              *string `gorm:"column:tax_id;type:character varying(100)" json:"tax_id"`
	PropFirstName      string  `gorm:"column:prop_first_name;type:character varying(100);not null" json:"prop_first_name"`
	PropLastName       string  `gorm:"column:prop_last_name;type:character varying(100);not null" json:"prop_last_name"`
	PropEmail          string  `gorm:"column:prop_email;type:character varying(255);not null" json:"prop_email"`
	PropNationalID     *string `gorm:"column:prop_national_id;type:character varying(100)" json:"prop_national_id"`
}

func (*BusinessCustomer) TableName() string { return TableNameBusinessCustomer }
