// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CustomerType int16     `gorm:"column:customer_type;type:smallint;not null" json:"customer_type"`
	FirstName    string    `gorm:"column:first_name;type:character varying(100);not null" json:"first_name"`
	LastName     string    `gorm:"column:last_name;type:character varying(100);not null" json:"last_name"`
	FullName     *string   `gorm:"column:full_name;type:character varying(255)" json:"full_name"`
	Email        string    `gorm:"column:email;type:character varying(255);not null;uniqueIndex:idx_customers_email,priority:1" json:"email"`
	KycStatus    int16     `gorm:"column:kyc_status;type:smallint;not null;index:idx_customers_kyc_status,priority:1" json:"kyc_status"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamptz;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamptz;not null;default:now()" json:"updated_at"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
