// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomerBusinessDetail = "customer_business_details"

// CustomerBusinessDetail mapped from table <customer_business_details>
type CustomerBusinessDetail struct {
	ID                 int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CustomerID         int64   `gorm:"column:customer_id;type:bigint;not null;uniqueIndex:idx_business_details_customer_id,priority:1" json:"customer_id"`
	CompanyName        string  `gorm:"column:company_name;type:character varying(255);not null" json:"company_name"`
	RegistrationNumber *string `gorm:"column:registration_number;type:character varying(100)" json:"registration_number"`
	TaxID              *string `gorm:"column:tax_id;type:character varying(100)" json:"tax_id"`
}

// TableName CustomerBusinessDetail's table name
func (*CustomerBusinessDetail) TableName() string {
	return TableNameCustomerBusinessDetail
}
