// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomerPhone = "customer_phones"

// CustomerPhone mapped from table <customer_phones>
type CustomerPhone struct {
	ID          int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CustomerID  int64  `gorm:"column:customer_id;type:bigint;not null;index:idx_customer_phones_customer_id,priority:1" json:"customer_id"`
	PhoneType   int16  `gorm:"column:phone_type;type:smallint;not null" json:"phone_type"`
	CountryCode string `gorm:"column:country_code;type:character varying(8);not null" json:"country_code"`
	Number      string `gorm:"column:number;type:character varying(30);not null" json:"number"`
	IsPrimary   bool   `gorm:"column:is_primary;type:boolean;not null" json:"is_primary"`
}

// TableName CustomerPhone's table name
func (*CustomerPhone) TableName() string {
	return TableNameCustomerPhone
}
