// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCustomerIndividualDetail = "customer_individual_details"

// CustomerIndividualDetail mapped from table <customer_individual_details>
type CustomerIndividualDetail struct {
	ID          int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CustomerID  int64      `gorm:"column:customer_id;type:bigint;not null;uniqueIndex:idx_individual_details_customer_id,priority:1" json:"customer_id"`
	DateOfBirth *time.Time `gorm:"column:date_of_birth;type:date" json:"date_of_birth"`
	Nationality *string    `gorm:"column:nationality;type:character(2)" json:"nationality"`
	NationalID  *string    `gorm:"column:national_id;type:character varying(100)" json:"national_id"`
}

// TableName CustomerIndividualDetail's table name
func (*CustomerIndividualDetail) TableName() string {
	return TableNameCustomerIndividualDetail
}
