// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameIndividualCustomer = "individual_customers"

// IndividualCustomer mapped from table <individual_customers>
type IndividualCustomer struct {
	ID           int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	DateOfBirth  *time.Time `gorm:"column:date_of_birth;type:date" json:"date_of_birth"`
	Nationality  *string    `gorm:"column:nationality;type:character(2)" json:"nationality"`
	NationalID   *string    `gorm:"column:national_id;type:character varying(100)" json:"national_id"`
}

func (*IndividualCustomer) TableName() string { return TableNameIndividualCustomer }
