// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePhone = "phones"

// Phone mapped from table <phones>
type Phone struct {
	ID          int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	PhoneType   int16  `gorm:"column:phone_type;type:smallint;not null" json:"phone_type"`
	CountryCode string `gorm:"column:country_code;type:character varying(8);not null" json:"country_code"`
	Number      string `gorm:"column:number;type:character varying(30);not null" json:"number"`
	IsPrimary   bool   `gorm:"column:is_primary;type:boolean;not null" json:"is_primary"`
}

func (*Phone) TableName() string { return TableNamePhone }
