// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRelContact = "rel_contact"

// RelContact mapped from table <rel_contact>
type RelContact struct {
	ID          int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ContactID   int64 `gorm:"column:contact_id;type:bigint;not null;index:idx_rel_contact_contact,priority:1" json:"contact_id"`
	ContactType int16 `gorm:"column:contact_type;type:smallint;not null;index:idx_rel_contact_contact,priority:2" json:"contact_type"`
	LinkID      int64 `gorm:"column:link_id;type:bigint;not null;index:idx_rel_contact_link,priority:1" json:"link_id"`
	LinkType    int16 `gorm:"column:link_type;type:smallint;not null;index:idx_rel_contact_link,priority:2" json:"link_type"`
}

func (*RelContact) TableName() string { return TableNameRelContact }
