// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/common/common.proto

// common/v1 holds types shared across every service. Defining them once here
// keeps a multi-module system coherent — Money means the same thing in
// Account, Ledger, and Transaction because they all import this one file.

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Money is always represented in integer minor units (paise, cents) plus an
// ISO-4217 currency code. Floats are never used for money anywhere in the
// system — this type enforces that at the contract level.
type Money struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount in the smallest indivisible unit of the currency.
	// e.g. ₹1000.00 -> amount_minor = 100000 ; currency = "INR".
	AmountMinor int64 `protobuf:"varint,1,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	// ISO-4217 currency code, e.g. "INR", "USD".
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_v1_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_v1_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// PageRequest is the standard pagination input for List RPCs.
type PageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max items to return (server caps this). 0 -> server default.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque cursor from a previous response. Empty -> first page.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_v1_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_v1_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// PageResponse carries the cursor for the next page.
type PageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pass this as page_token in the next request. Empty -> no more pages.
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total matching records, if the server chooses to compute it.
	TotalSize     int64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_v1_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_v1_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *PageResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PageResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// Phone represents a single phone number with its classification.
// A customer or contact must supply at least one phone entry.
// is_primary marks the preferred number for outbound contact.
type Phone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  PhoneType              `protobuf:"varint,1,opt,name=type,proto3,enum=common.v1.PhoneType" json:"type,omitempty"`
	// E.164 country code prefix, e.g. "+91", "+1".
	CountryCode string `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// Local number without the country code, e.g. "9876543210".
	Number string `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	// Exactly one phone per contact set should have is_primary = true.
	IsPrimary     bool `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Phone) Reset() {
	*x = Phone{}
	mi := &file_v1_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Phone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phone) ProtoMessage() {}

func (x *Phone) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phone.ProtoReflect.Descriptor instead.
func (*Phone) Descriptor() ([]byte, []int) {
	return file_v1_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *Phone) GetType() PhoneType {
	if x != nil {
		return x.Type
	}
	return PhoneType_PHONE_TYPE_UNSPECIFIED
}

func (x *Phone) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Phone) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Phone) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

// Address represents a postal address with its classification.
// A customer must supply at least one address entry.
// is_primary marks the address used for official correspondence by default.
type Address struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Type       AddressType            `protobuf:"varint,1,opt,name=type,proto3,enum=common.v1.AddressType" json:"type,omitempty"`
	Line1      string                 `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2      string                 `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"` // optional — apartment, suite, floor, etc.
	City       string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State      string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"` // state, province, or region
	PostalCode string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	// ISO 3166-1 alpha-2 country code, e.g. "IN", "US".
	Country       string `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	IsPrimary     bool   `protobuf:"varint,8,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_v1_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_v1_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *Address) GetType() AddressType {
	if x != nil {
		return x.Type
	}
	return AddressType_ADDRESS_TYPE_UNSPECIFIED
}

func (x *Address) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Address) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

var File_v1_common_common_proto protoreflect.FileDescriptor

const file_v1_common_common_proto_rawDesc = "" +
	"\n" +
	"\x16v1/common/common.proto\x12\tcommon.v1\x1a\x15v1/common/enums.proto\"F\n" +
	"\x05Money\x12!\n" +
	"\famount_minor\x18\x01 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"I\n" +
	"\vPageRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"U\n" +
	"\fPageResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\"\x8b\x01\n" +
	"\x05Phone\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.common.v1.PhoneTypeR\x04type\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\"\xe5\x01\n" +
	"\aAddress\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.common.v1.AddressTypeR\x04type\x12\x14\n" +
	"\x05line1\x18\x02 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x03 \x01(\tR\x05line2\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1d\n" +
	"\n" +
	"is_primary\x18\b \x01(\bR\tisPrimaryB7Z5github.com/visvesh-ramesh/corebank/v1/common;commonv1b\x06proto3"

var (
	file_v1_common_common_proto_rawDescOnce sync.Once
	file_v1_common_common_proto_rawDescData []byte
)

func file_v1_common_common_proto_rawDescGZIP() []byte {
	file_v1_common_common_proto_rawDescOnce.Do(func() {
		file_v1_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_common_common_proto_rawDesc), len(file_v1_common_common_proto_rawDesc)))
	})
	return file_v1_common_common_proto_rawDescData
}

var file_v1_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_common_common_proto_goTypes = []any{
	(*Money)(nil),        // 0: common.v1.Money
	(*PageRequest)(nil),  // 1: common.v1.PageRequest
	(*PageResponse)(nil), // 2: common.v1.PageResponse
	(*Phone)(nil),        // 3: common.v1.Phone
	(*Address)(nil),      // 4: common.v1.Address
	(PhoneType)(0),       // 5: common.v1.PhoneType
	(AddressType)(0),     // 6: common.v1.AddressType
}
var file_v1_common_common_proto_depIdxs = []int32{
	5, // 0: common.v1.Phone.type:type_name -> common.v1.PhoneType
	6, // 1: common.v1.Address.type:type_name -> common.v1.AddressType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_common_common_proto_init() }
func file_v1_common_common_proto_init() {
	if File_v1_common_common_proto != nil {
		return
	}
	file_v1_common_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_common_common_proto_rawDesc), len(file_v1_common_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_common_common_proto_goTypes,
		DependencyIndexes: file_v1_common_common_proto_depIdxs,
		MessageInfos:      file_v1_common_common_proto_msgTypes,
	}.Build()
	File_v1_common_common_proto = out.File
	file_v1_common_common_proto_goTypes = nil
	file_v1_common_common_proto_depIdxs = nil
}
