// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/common/enums.proto

// All domain enums across every service live here so there is one
// authoritative source. Each enum is prefixed with its domain to stay
// unambiguous inside the shared common.v1 package.

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KYCStatus is the regulated lifecycle of a customer record.
//
//	PENDING ──▶ VERIFIED ──▶ ACTIVE ──▶ SUSPENDED ──▶ ACTIVE
//	                             │
//	                             └──▶ CLOSED  (terminal — no hard delete)
type KYCStatus int32

const (
	KYCStatus_KYC_STATUS_UNSPECIFIED KYCStatus = 0
	KYCStatus_KYC_STATUS_PENDING     KYCStatus = 1 // onboarded, identity not yet verified
	KYCStatus_KYC_STATUS_VERIFIED    KYCStatus = 2 // KYC documents checked
	KYCStatus_KYC_STATUS_ACTIVE      KYCStatus = 3 // fully active, can hold accounts
	KYCStatus_KYC_STATUS_SUSPENDED   KYCStatus = 4 // temporarily frozen (e.g. compliance review)
	KYCStatus_KYC_STATUS_CLOSED      KYCStatus = 5 // terminal — no re-activation
)

// Enum value maps for KYCStatus.
var (
	KYCStatus_name = map[int32]string{
		0: "KYC_STATUS_UNSPECIFIED",
		1: "KYC_STATUS_PENDING",
		2: "KYC_STATUS_VERIFIED",
		3: "KYC_STATUS_ACTIVE",
		4: "KYC_STATUS_SUSPENDED",
		5: "KYC_STATUS_CLOSED",
	}
	KYCStatus_value = map[string]int32{
		"KYC_STATUS_UNSPECIFIED": 0,
		"KYC_STATUS_PENDING":     1,
		"KYC_STATUS_VERIFIED":    2,
		"KYC_STATUS_ACTIVE":      3,
		"KYC_STATUS_SUSPENDED":   4,
		"KYC_STATUS_CLOSED":      5,
	}
)

func (x KYCStatus) Enum() *KYCStatus {
	p := new(KYCStatus)
	*p = x
	return p
}

func (x KYCStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KYCStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[0].Descriptor()
}

func (KYCStatus) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[0]
}

func (x KYCStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KYCStatus.Descriptor instead.
func (KYCStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{0}
}

// CustomerType distinguishes individuals from businesses; used for product
// eligibility and KYC document requirements.
type CustomerType int32

const (
	CustomerType_CUSTOMER_TYPE_UNSPECIFIED CustomerType = 0
	CustomerType_CUSTOMER_TYPE_INDIVIDUAL  CustomerType = 1
	CustomerType_CUSTOMER_TYPE_BUSINESS    CustomerType = 2
)

// Enum value maps for CustomerType.
var (
	CustomerType_name = map[int32]string{
		0: "CUSTOMER_TYPE_UNSPECIFIED",
		1: "CUSTOMER_TYPE_INDIVIDUAL",
		2: "CUSTOMER_TYPE_BUSINESS",
	}
	CustomerType_value = map[string]int32{
		"CUSTOMER_TYPE_UNSPECIFIED": 0,
		"CUSTOMER_TYPE_INDIVIDUAL":  1,
		"CUSTOMER_TYPE_BUSINESS":    2,
	}
)

func (x CustomerType) Enum() *CustomerType {
	p := new(CustomerType)
	*p = x
	return p
}

func (x CustomerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomerType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[1].Descriptor()
}

func (CustomerType) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[1]
}

func (x CustomerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomerType.Descriptor instead.
func (CustomerType) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{1}
}

// PhoneType classifies a phone number so the system knows which line to call.
type PhoneType int32

const (
	PhoneType_PHONE_TYPE_UNSPECIFIED PhoneType = 0
	PhoneType_PHONE_TYPE_MOBILE      PhoneType = 1
	PhoneType_PHONE_TYPE_LANDLINE    PhoneType = 2
	PhoneType_PHONE_TYPE_WORK        PhoneType = 3
	PhoneType_PHONE_TYPE_FAX         PhoneType = 4
)

// Enum value maps for PhoneType.
var (
	PhoneType_name = map[int32]string{
		0: "PHONE_TYPE_UNSPECIFIED",
		1: "PHONE_TYPE_MOBILE",
		2: "PHONE_TYPE_LANDLINE",
		3: "PHONE_TYPE_WORK",
		4: "PHONE_TYPE_FAX",
	}
	PhoneType_value = map[string]int32{
		"PHONE_TYPE_UNSPECIFIED": 0,
		"PHONE_TYPE_MOBILE":      1,
		"PHONE_TYPE_LANDLINE":    2,
		"PHONE_TYPE_WORK":        3,
		"PHONE_TYPE_FAX":         4,
	}
)

func (x PhoneType) Enum() *PhoneType {
	p := new(PhoneType)
	*p = x
	return p
}

func (x PhoneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhoneType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[2].Descriptor()
}

func (PhoneType) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[2]
}

func (x PhoneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhoneType.Descriptor instead.
func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{2}
}

// AddressType classifies a postal address by its purpose.
type AddressType int32

const (
	AddressType_ADDRESS_TYPE_UNSPECIFIED    AddressType = 0
	AddressType_ADDRESS_TYPE_HOME           AddressType = 1
	AddressType_ADDRESS_TYPE_WORK           AddressType = 2
	AddressType_ADDRESS_TYPE_REGISTERED     AddressType = 3 // company-registered / legal address
	AddressType_ADDRESS_TYPE_CORRESPONDENCE AddressType = 4 // mailing / correspondence address
)

// Enum value maps for AddressType.
var (
	AddressType_name = map[int32]string{
		0: "ADDRESS_TYPE_UNSPECIFIED",
		1: "ADDRESS_TYPE_HOME",
		2: "ADDRESS_TYPE_WORK",
		3: "ADDRESS_TYPE_REGISTERED",
		4: "ADDRESS_TYPE_CORRESPONDENCE",
	}
	AddressType_value = map[string]int32{
		"ADDRESS_TYPE_UNSPECIFIED":    0,
		"ADDRESS_TYPE_HOME":           1,
		"ADDRESS_TYPE_WORK":           2,
		"ADDRESS_TYPE_REGISTERED":     3,
		"ADDRESS_TYPE_CORRESPONDENCE": 4,
	}
)

func (x AddressType) Enum() *AddressType {
	p := new(AddressType)
	*p = x
	return p
}

func (x AddressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[3].Descriptor()
}

func (AddressType) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[3]
}

func (x AddressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressType.Descriptor instead.
func (AddressType) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{3}
}

// AccountType determines product behaviour — overdraft rules, interest,
// whether the balance may go negative, etc.
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_SAVINGS     AccountType = 1 // balance cannot go below zero
	AccountType_ACCOUNT_TYPE_CURRENT     AccountType = 2 // may permit an overdraft up to the limit
	AccountType_ACCOUNT_TYPE_WALLET      AccountType = 3 // prepaid; balance only
	AccountType_ACCOUNT_TYPE_LOAN        AccountType = 4 // balance represents outstanding principal
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_SAVINGS",
		2: "ACCOUNT_TYPE_CURRENT",
		3: "ACCOUNT_TYPE_WALLET",
		4: "ACCOUNT_TYPE_LOAN",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_SAVINGS":     1,
		"ACCOUNT_TYPE_CURRENT":     2,
		"ACCOUNT_TYPE_WALLET":      3,
		"ACCOUNT_TYPE_LOAN":        4,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[4].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[4]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{4}
}

// AccountStatus is the account lifecycle state machine.
//
//	PENDING ──▶ ACTIVE ──▶ FROZEN ──▶ ACTIVE
//	               │
//	               └──▶ CLOSED  (terminal; requires zero balance)
type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_PENDING     AccountStatus = 1 // created, not yet activated
	AccountStatus_ACCOUNT_STATUS_ACTIVE      AccountStatus = 2 // normal operation
	AccountStatus_ACCOUNT_STATUS_FROZEN      AccountStatus = 3 // no debits/credits (compliance, dispute)
	AccountStatus_ACCOUNT_STATUS_CLOSED      AccountStatus = 4 // terminal; only allowed when balance is zero
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_PENDING",
		2: "ACCOUNT_STATUS_ACTIVE",
		3: "ACCOUNT_STATUS_FROZEN",
		4: "ACCOUNT_STATUS_CLOSED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_PENDING":     1,
		"ACCOUNT_STATUS_ACTIVE":      2,
		"ACCOUNT_STATUS_FROZEN":      3,
		"ACCOUNT_STATUS_CLOSED":      4,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[5].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[5]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{5}
}

// EntryDirection is the sign of a single ledger entry against an account.
// DEBIT decreases; CREDIT increases. The signed sum across a transaction
// must be zero — that is the double-entry invariant.
type EntryDirection int32

const (
	EntryDirection_ENTRY_DIRECTION_UNSPECIFIED EntryDirection = 0
	EntryDirection_ENTRY_DIRECTION_DEBIT       EntryDirection = 1
	EntryDirection_ENTRY_DIRECTION_CREDIT      EntryDirection = 2
)

// Enum value maps for EntryDirection.
var (
	EntryDirection_name = map[int32]string{
		0: "ENTRY_DIRECTION_UNSPECIFIED",
		1: "ENTRY_DIRECTION_DEBIT",
		2: "ENTRY_DIRECTION_CREDIT",
	}
	EntryDirection_value = map[string]int32{
		"ENTRY_DIRECTION_UNSPECIFIED": 0,
		"ENTRY_DIRECTION_DEBIT":       1,
		"ENTRY_DIRECTION_CREDIT":      2,
	}
)

func (x EntryDirection) Enum() *EntryDirection {
	p := new(EntryDirection)
	*p = x
	return p
}

func (x EntryDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[6].Descriptor()
}

func (EntryDirection) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[6]
}

func (x EntryDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryDirection.Descriptor instead.
func (EntryDirection) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{6}
}

// LedgerTransactionStatus reflects whether a posted ledger transaction was
// applied. A transaction is atomic: all entries apply, or none do.
type LedgerTransactionStatus int32

const (
	LedgerTransactionStatus_LEDGER_TRANSACTION_STATUS_UNSPECIFIED LedgerTransactionStatus = 0
	LedgerTransactionStatus_LEDGER_TRANSACTION_STATUS_POSTED      LedgerTransactionStatus = 1 // applied successfully
	LedgerTransactionStatus_LEDGER_TRANSACTION_STATUS_REJECTED    LedgerTransactionStatus = 2 // failed validation — nothing written
)

// Enum value maps for LedgerTransactionStatus.
var (
	LedgerTransactionStatus_name = map[int32]string{
		0: "LEDGER_TRANSACTION_STATUS_UNSPECIFIED",
		1: "LEDGER_TRANSACTION_STATUS_POSTED",
		2: "LEDGER_TRANSACTION_STATUS_REJECTED",
	}
	LedgerTransactionStatus_value = map[string]int32{
		"LEDGER_TRANSACTION_STATUS_UNSPECIFIED": 0,
		"LEDGER_TRANSACTION_STATUS_POSTED":      1,
		"LEDGER_TRANSACTION_STATUS_REJECTED":    2,
	}
)

func (x LedgerTransactionStatus) Enum() *LedgerTransactionStatus {
	p := new(LedgerTransactionStatus)
	*p = x
	return p
}

func (x LedgerTransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerTransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[7].Descriptor()
}

func (LedgerTransactionStatus) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[7]
}

func (x LedgerTransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerTransactionStatus.Descriptor instead.
func (LedgerTransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{7}
}

// TransactionKind is the business-level operation a caller initiated.
// The orchestrator maps each kind to a balanced set of ledger entries.
type TransactionKind int32

const (
	TransactionKind_TRANSACTION_KIND_UNSPECIFIED TransactionKind = 0
	TransactionKind_TRANSACTION_KIND_TRANSFER    TransactionKind = 1 // account → account
	TransactionKind_TRANSACTION_KIND_DEPOSIT     TransactionKind = 2 // external → account
	TransactionKind_TRANSACTION_KIND_WITHDRAWAL  TransactionKind = 3 // account → external
	TransactionKind_TRANSACTION_KIND_REVERSAL    TransactionKind = 4 // undo a prior transaction
)

// Enum value maps for TransactionKind.
var (
	TransactionKind_name = map[int32]string{
		0: "TRANSACTION_KIND_UNSPECIFIED",
		1: "TRANSACTION_KIND_TRANSFER",
		2: "TRANSACTION_KIND_DEPOSIT",
		3: "TRANSACTION_KIND_WITHDRAWAL",
		4: "TRANSACTION_KIND_REVERSAL",
	}
	TransactionKind_value = map[string]int32{
		"TRANSACTION_KIND_UNSPECIFIED": 0,
		"TRANSACTION_KIND_TRANSFER":    1,
		"TRANSACTION_KIND_DEPOSIT":     2,
		"TRANSACTION_KIND_WITHDRAWAL":  3,
		"TRANSACTION_KIND_REVERSAL":    4,
	}
)

func (x TransactionKind) Enum() *TransactionKind {
	p := new(TransactionKind)
	*p = x
	return p
}

func (x TransactionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[8].Descriptor()
}

func (TransactionKind) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[8]
}

func (x TransactionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionKind.Descriptor instead.
func (TransactionKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{8}
}

// TransactionState tracks the orchestration saga lifecycle. A FAILED
// transaction guarantees no net money was moved.
type TransactionState int32

const (
	TransactionState_TRANSACTION_STATE_UNSPECIFIED TransactionState = 0
	TransactionState_TRANSACTION_STATE_PENDING     TransactionState = 1 // accepted, orchestration in progress
	TransactionState_TRANSACTION_STATE_COMPLETED   TransactionState = 2 // ledger posted successfully
	TransactionState_TRANSACTION_STATE_FAILED      TransactionState = 3 // rejected or compensated; no net movement
)

// Enum value maps for TransactionState.
var (
	TransactionState_name = map[int32]string{
		0: "TRANSACTION_STATE_UNSPECIFIED",
		1: "TRANSACTION_STATE_PENDING",
		2: "TRANSACTION_STATE_COMPLETED",
		3: "TRANSACTION_STATE_FAILED",
	}
	TransactionState_value = map[string]int32{
		"TRANSACTION_STATE_UNSPECIFIED": 0,
		"TRANSACTION_STATE_PENDING":     1,
		"TRANSACTION_STATE_COMPLETED":   2,
		"TRANSACTION_STATE_FAILED":      3,
	}
)

func (x TransactionState) Enum() *TransactionState {
	p := new(TransactionState)
	*p = x
	return p
}

func (x TransactionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionState) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[9].Descriptor()
}

func (TransactionState) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[9]
}

func (x TransactionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionState.Descriptor instead.
func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{9}
}

// ProductClass is the top-level category of a bank product. It determines
// which configuration block (oneof) applies on the Product message.
type ProductClass int32

const (
	ProductClass_PRODUCT_CLASS_UNSPECIFIED ProductClass = 0
	ProductClass_PRODUCT_CLASS_DEPOSIT     ProductClass = 1 // money the customer owns (savings, current, term)
	ProductClass_PRODUCT_CLASS_LOAN        ProductClass = 2 // money the customer owes
	ProductClass_PRODUCT_CLASS_CARD        ProductClass = 3 // credit/prepaid card products
)

// Enum value maps for ProductClass.
var (
	ProductClass_name = map[int32]string{
		0: "PRODUCT_CLASS_UNSPECIFIED",
		1: "PRODUCT_CLASS_DEPOSIT",
		2: "PRODUCT_CLASS_LOAN",
		3: "PRODUCT_CLASS_CARD",
	}
	ProductClass_value = map[string]int32{
		"PRODUCT_CLASS_UNSPECIFIED": 0,
		"PRODUCT_CLASS_DEPOSIT":     1,
		"PRODUCT_CLASS_LOAN":        2,
		"PRODUCT_CLASS_CARD":        3,
	}
)

func (x ProductClass) Enum() *ProductClass {
	p := new(ProductClass)
	*p = x
	return p
}

func (x ProductClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductClass) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[10].Descriptor()
}

func (ProductClass) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[10]
}

func (x ProductClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductClass.Descriptor instead.
func (ProductClass) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{10}
}

// ProductStatus controls whether new accounts may be opened against a product.
// Existing accounts are unaffected when a product is retired.
type ProductStatus int32

const (
	ProductStatus_PRODUCT_STATUS_UNSPECIFIED ProductStatus = 0
	ProductStatus_PRODUCT_STATUS_DRAFT       ProductStatus = 1 // being configured, not yet sellable
	ProductStatus_PRODUCT_STATUS_ACTIVE      ProductStatus = 2 // open for new accounts
	ProductStatus_PRODUCT_STATUS_RETIRED     ProductStatus = 3 // no new accounts; existing ones continue
)

// Enum value maps for ProductStatus.
var (
	ProductStatus_name = map[int32]string{
		0: "PRODUCT_STATUS_UNSPECIFIED",
		1: "PRODUCT_STATUS_DRAFT",
		2: "PRODUCT_STATUS_ACTIVE",
		3: "PRODUCT_STATUS_RETIRED",
	}
	ProductStatus_value = map[string]int32{
		"PRODUCT_STATUS_UNSPECIFIED": 0,
		"PRODUCT_STATUS_DRAFT":       1,
		"PRODUCT_STATUS_ACTIVE":      2,
		"PRODUCT_STATUS_RETIRED":     3,
	}
)

func (x ProductStatus) Enum() *ProductStatus {
	p := new(ProductStatus)
	*p = x
	return p
}

func (x ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[11].Descriptor()
}

func (ProductStatus) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[11]
}

func (x ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductStatus.Descriptor instead.
func (ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{11}
}

// DepositKind is the sub-type of a deposit product.
type DepositKind int32

const (
	DepositKind_DEPOSIT_KIND_UNSPECIFIED DepositKind = 0
	DepositKind_DEPOSIT_KIND_SAVINGS     DepositKind = 1
	DepositKind_DEPOSIT_KIND_CURRENT     DepositKind = 2
	DepositKind_DEPOSIT_KIND_TERM        DepositKind = 3 // fixed / recurring deposit
)

// Enum value maps for DepositKind.
var (
	DepositKind_name = map[int32]string{
		0: "DEPOSIT_KIND_UNSPECIFIED",
		1: "DEPOSIT_KIND_SAVINGS",
		2: "DEPOSIT_KIND_CURRENT",
		3: "DEPOSIT_KIND_TERM",
	}
	DepositKind_value = map[string]int32{
		"DEPOSIT_KIND_UNSPECIFIED": 0,
		"DEPOSIT_KIND_SAVINGS":     1,
		"DEPOSIT_KIND_CURRENT":     2,
		"DEPOSIT_KIND_TERM":        3,
	}
)

func (x DepositKind) Enum() *DepositKind {
	p := new(DepositKind)
	*p = x
	return p
}

func (x DepositKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepositKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[12].Descriptor()
}

func (DepositKind) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[12]
}

func (x DepositKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepositKind.Descriptor instead.
func (DepositKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{12}
}

// InterestCalcMethod determines how interest accrues on a deposit product.
type InterestCalcMethod int32

const (
	InterestCalcMethod_INTEREST_CALC_METHOD_UNSPECIFIED   InterestCalcMethod = 0
	InterestCalcMethod_INTEREST_CALC_METHOD_DAILY_BALANCE InterestCalcMethod = 1 // accrue on daily closing balance
	InterestCalcMethod_INTEREST_CALC_METHOD_MIN_MONTHLY   InterestCalcMethod = 2 // on minimum monthly balance (legacy)
	InterestCalcMethod_INTEREST_CALC_METHOD_NONE          InterestCalcMethod = 3 // non-interest-bearing (e.g. wallet)
)

// Enum value maps for InterestCalcMethod.
var (
	InterestCalcMethod_name = map[int32]string{
		0: "INTEREST_CALC_METHOD_UNSPECIFIED",
		1: "INTEREST_CALC_METHOD_DAILY_BALANCE",
		2: "INTEREST_CALC_METHOD_MIN_MONTHLY",
		3: "INTEREST_CALC_METHOD_NONE",
	}
	InterestCalcMethod_value = map[string]int32{
		"INTEREST_CALC_METHOD_UNSPECIFIED":   0,
		"INTEREST_CALC_METHOD_DAILY_BALANCE": 1,
		"INTEREST_CALC_METHOD_MIN_MONTHLY":   2,
		"INTEREST_CALC_METHOD_NONE":          3,
	}
)

func (x InterestCalcMethod) Enum() *InterestCalcMethod {
	p := new(InterestCalcMethod)
	*p = x
	return p
}

func (x InterestCalcMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterestCalcMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[13].Descriptor()
}

func (InterestCalcMethod) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[13]
}

func (x InterestCalcMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterestCalcMethod.Descriptor instead.
func (InterestCalcMethod) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{13}
}

// InterestType for loan products: whether the rate is locked or tracks a
// benchmark.
type InterestType int32

const (
	InterestType_INTEREST_TYPE_UNSPECIFIED InterestType = 0
	InterestType_INTEREST_TYPE_FIXED       InterestType = 1 // rate fixed for the tenure
	InterestType_INTEREST_TYPE_FLOATING    InterestType = 2 // rate tracks a benchmark + spread
)

// Enum value maps for InterestType.
var (
	InterestType_name = map[int32]string{
		0: "INTEREST_TYPE_UNSPECIFIED",
		1: "INTEREST_TYPE_FIXED",
		2: "INTEREST_TYPE_FLOATING",
	}
	InterestType_value = map[string]int32{
		"INTEREST_TYPE_UNSPECIFIED": 0,
		"INTEREST_TYPE_FIXED":       1,
		"INTEREST_TYPE_FLOATING":    2,
	}
)

func (x InterestType) Enum() *InterestType {
	p := new(InterestType)
	*p = x
	return p
}

func (x InterestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterestType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[14].Descriptor()
}

func (InterestType) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[14]
}

func (x InterestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterestType.Descriptor instead.
func (InterestType) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{14}
}

// RateBenchmark is the external index a floating-rate loan tracks.
type RateBenchmark int32

const (
	RateBenchmark_RATE_BENCHMARK_UNSPECIFIED RateBenchmark = 0
	RateBenchmark_RATE_BENCHMARK_NONE        RateBenchmark = 1 // used with FIXED interest type
	RateBenchmark_RATE_BENCHMARK_REPO        RateBenchmark = 2 // RBI repo rate
	RateBenchmark_RATE_BENCHMARK_MCLR        RateBenchmark = 3 // marginal cost of funds lending rate
)

// Enum value maps for RateBenchmark.
var (
	RateBenchmark_name = map[int32]string{
		0: "RATE_BENCHMARK_UNSPECIFIED",
		1: "RATE_BENCHMARK_NONE",
		2: "RATE_BENCHMARK_REPO",
		3: "RATE_BENCHMARK_MCLR",
	}
	RateBenchmark_value = map[string]int32{
		"RATE_BENCHMARK_UNSPECIFIED": 0,
		"RATE_BENCHMARK_NONE":        1,
		"RATE_BENCHMARK_REPO":        2,
		"RATE_BENCHMARK_MCLR":        3,
	}
)

func (x RateBenchmark) Enum() *RateBenchmark {
	p := new(RateBenchmark)
	*p = x
	return p
}

func (x RateBenchmark) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateBenchmark) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[15].Descriptor()
}

func (RateBenchmark) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[15]
}

func (x RateBenchmark) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateBenchmark.Descriptor instead.
func (RateBenchmark) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{15}
}

// AmortizationMethod determines how loan repayments are structured.
type AmortizationMethod int32

const (
	AmortizationMethod_AMORTIZATION_METHOD_UNSPECIFIED      AmortizationMethod = 0
	AmortizationMethod_AMORTIZATION_METHOD_REDUCING_BALANCE AmortizationMethod = 1 // EMI on reducing principal (standard)
	AmortizationMethod_AMORTIZATION_METHOD_FLAT             AmortizationMethod = 2 // flat-rate (rare, regulated)
	AmortizationMethod_AMORTIZATION_METHOD_BULLET           AmortizationMethod = 3 // interest periodic, principal at end
)

// Enum value maps for AmortizationMethod.
var (
	AmortizationMethod_name = map[int32]string{
		0: "AMORTIZATION_METHOD_UNSPECIFIED",
		1: "AMORTIZATION_METHOD_REDUCING_BALANCE",
		2: "AMORTIZATION_METHOD_FLAT",
		3: "AMORTIZATION_METHOD_BULLET",
	}
	AmortizationMethod_value = map[string]int32{
		"AMORTIZATION_METHOD_UNSPECIFIED":      0,
		"AMORTIZATION_METHOD_REDUCING_BALANCE": 1,
		"AMORTIZATION_METHOD_FLAT":             2,
		"AMORTIZATION_METHOD_BULLET":           3,
	}
)

func (x AmortizationMethod) Enum() *AmortizationMethod {
	p := new(AmortizationMethod)
	*p = x
	return p
}

func (x AmortizationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AmortizationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_enums_proto_enumTypes[16].Descriptor()
}

func (AmortizationMethod) Type() protoreflect.EnumType {
	return &file_v1_common_enums_proto_enumTypes[16]
}

func (x AmortizationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AmortizationMethod.Descriptor instead.
func (AmortizationMethod) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_enums_proto_rawDescGZIP(), []int{16}
}

var File_v1_common_enums_proto protoreflect.FileDescriptor

const file_v1_common_enums_proto_rawDesc = "" +
	"\n" +
	"\x15v1/common/enums.proto\x12\tcommon.v1*\xa0\x01\n" +
	"\tKYCStatus\x12\x1a\n" +
	"\x16KYC_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12KYC_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13KYC_STATUS_VERIFIED\x10\x02\x12\x15\n" +
	"\x11KYC_STATUS_ACTIVE\x10\x03\x12\x18\n" +
	"\x14KYC_STATUS_SUSPENDED\x10\x04\x12\x15\n" +
	"\x11KYC_STATUS_CLOSED\x10\x05*g\n" +
	"\fCustomerType\x12\x1d\n" +
	"\x19CUSTOMER_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CUSTOMER_TYPE_INDIVIDUAL\x10\x01\x12\x1a\n" +
	"\x16CUSTOMER_TYPE_BUSINESS\x10\x02*\x80\x01\n" +
	"\tPhoneType\x12\x1a\n" +
	"\x16PHONE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PHONE_TYPE_MOBILE\x10\x01\x12\x17\n" +
	"\x13PHONE_TYPE_LANDLINE\x10\x02\x12\x13\n" +
	"\x0fPHONE_TYPE_WORK\x10\x03\x12\x12\n" +
	"\x0ePHONE_TYPE_FAX\x10\x04*\x97\x01\n" +
	"\vAddressType\x12\x1c\n" +
	"\x18ADDRESS_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ADDRESS_TYPE_HOME\x10\x01\x12\x15\n" +
	"\x11ADDRESS_TYPE_WORK\x10\x02\x12\x1b\n" +
	"\x17ADDRESS_TYPE_REGISTERED\x10\x03\x12\x1f\n" +
	"\x1bADDRESS_TYPE_CORRESPONDENCE\x10\x04*\x8f\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACCOUNT_TYPE_SAVINGS\x10\x01\x12\x18\n" +
	"\x14ACCOUNT_TYPE_CURRENT\x10\x02\x12\x17\n" +
	"\x13ACCOUNT_TYPE_WALLET\x10\x03\x12\x15\n" +
	"\x11ACCOUNT_TYPE_LOAN\x10\x04*\x9c\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ACCOUNT_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_STATUS_FROZEN\x10\x03\x12\x19\n" +
	"\x15ACCOUNT_STATUS_CLOSED\x10\x04*h\n" +
	"\x0eEntryDirection\x12\x1f\n" +
	"\x1bENTRY_DIRECTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ENTRY_DIRECTION_DEBIT\x10\x01\x12\x1a\n" +
	"\x16ENTRY_DIRECTION_CREDIT\x10\x02*\x92\x01\n" +
	"\x17LedgerTransactionStatus\x12)\n" +
	"%LEDGER_TRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12$\n" +
	" LEDGER_TRANSACTION_STATUS_POSTED\x10\x01\x12&\n" +
	"\"LEDGER_TRANSACTION_STATUS_REJECTED\x10\x02*\xb0\x01\n" +
	"\x0fTransactionKind\x12 \n" +
	"\x1cTRANSACTION_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TRANSACTION_KIND_TRANSFER\x10\x01\x12\x1c\n" +
	"\x18TRANSACTION_KIND_DEPOSIT\x10\x02\x12\x1f\n" +
	"\x1bTRANSACTION_KIND_WITHDRAWAL\x10\x03\x12\x1d\n" +
	"\x19TRANSACTION_KIND_REVERSAL\x10\x04*\x93\x01\n" +
	"\x10TransactionState\x12!\n" +
	"\x1dTRANSACTION_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TRANSACTION_STATE_PENDING\x10\x01\x12\x1f\n" +
	"\x1bTRANSACTION_STATE_COMPLETED\x10\x02\x12\x1c\n" +
	"\x18TRANSACTION_STATE_FAILED\x10\x03*x\n" +
	"\fProductClass\x12\x1d\n" +
	"\x19PRODUCT_CLASS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PRODUCT_CLASS_DEPOSIT\x10\x01\x12\x16\n" +
	"\x12PRODUCT_CLASS_LOAN\x10\x02\x12\x16\n" +
	"\x12PRODUCT_CLASS_CARD\x10\x03*\x80\x01\n" +
	"\rProductStatus\x12\x1e\n" +
	"\x1aPRODUCT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PRODUCT_STATUS_DRAFT\x10\x01\x12\x19\n" +
	"\x15PRODUCT_STATUS_ACTIVE\x10\x02\x12\x1a\n" +
	"\x16PRODUCT_STATUS_RETIRED\x10\x03*v\n" +
	"\vDepositKind\x12\x1c\n" +
	"\x18DEPOSIT_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DEPOSIT_KIND_SAVINGS\x10\x01\x12\x18\n" +
	"\x14DEPOSIT_KIND_CURRENT\x10\x02\x12\x15\n" +
	"\x11DEPOSIT_KIND_TERM\x10\x03*\xa7\x01\n" +
	"\x12InterestCalcMethod\x12$\n" +
	" INTEREST_CALC_METHOD_UNSPECIFIED\x10\x00\x12&\n" +
	"\"INTEREST_CALC_METHOD_DAILY_BALANCE\x10\x01\x12$\n" +
	" INTEREST_CALC_METHOD_MIN_MONTHLY\x10\x02\x12\x1d\n" +
	"\x19INTEREST_CALC_METHOD_NONE\x10\x03*b\n" +
	"\fInterestType\x12\x1d\n" +
	"\x19INTEREST_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13INTEREST_TYPE_FIXED\x10\x01\x12\x1a\n" +
	"\x16INTEREST_TYPE_FLOATING\x10\x02*z\n" +
	"\rRateBenchmark\x12\x1e\n" +
	"\x1aRATE_BENCHMARK_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RATE_BENCHMARK_NONE\x10\x01\x12\x17\n" +
	"\x13RATE_BENCHMARK_REPO\x10\x02\x12\x17\n" +
	"\x13RATE_BENCHMARK_MCLR\x10\x03*\xa1\x01\n" +
	"\x12AmortizationMethod\x12#\n" +
	"\x1fAMORTIZATION_METHOD_UNSPECIFIED\x10\x00\x12(\n" +
	"$AMORTIZATION_METHOD_REDUCING_BALANCE\x10\x01\x12\x1c\n" +
	"\x18AMORTIZATION_METHOD_FLAT\x10\x02\x12\x1e\n" +
	"\x1aAMORTIZATION_METHOD_BULLET\x10\x03B7Z5github.com/visvesh-ramesh/corebank/v1/common;commonv1b\x06proto3"

var (
	file_v1_common_enums_proto_rawDescOnce sync.Once
	file_v1_common_enums_proto_rawDescData []byte
)

func file_v1_common_enums_proto_rawDescGZIP() []byte {
	file_v1_common_enums_proto_rawDescOnce.Do(func() {
		file_v1_common_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_common_enums_proto_rawDesc), len(file_v1_common_enums_proto_rawDesc)))
	})
	return file_v1_common_enums_proto_rawDescData
}

var file_v1_common_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 17)
var file_v1_common_enums_proto_goTypes = []any{
	(KYCStatus)(0),               // 0: common.v1.KYCStatus
	(CustomerType)(0),            // 1: common.v1.CustomerType
	(PhoneType)(0),               // 2: common.v1.PhoneType
	(AddressType)(0),             // 3: common.v1.AddressType
	(AccountType)(0),             // 4: common.v1.AccountType
	(AccountStatus)(0),           // 5: common.v1.AccountStatus
	(EntryDirection)(0),          // 6: common.v1.EntryDirection
	(LedgerTransactionStatus)(0), // 7: common.v1.LedgerTransactionStatus
	(TransactionKind)(0),         // 8: common.v1.TransactionKind
	(TransactionState)(0),        // 9: common.v1.TransactionState
	(ProductClass)(0),            // 10: common.v1.ProductClass
	(ProductStatus)(0),           // 11: common.v1.ProductStatus
	(DepositKind)(0),             // 12: common.v1.DepositKind
	(InterestCalcMethod)(0),      // 13: common.v1.InterestCalcMethod
	(InterestType)(0),            // 14: common.v1.InterestType
	(RateBenchmark)(0),           // 15: common.v1.RateBenchmark
	(AmortizationMethod)(0),      // 16: common.v1.AmortizationMethod
}
var file_v1_common_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_common_enums_proto_init() }
func file_v1_common_enums_proto_init() {
	if File_v1_common_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_common_enums_proto_rawDesc), len(file_v1_common_enums_proto_rawDesc)),
			NumEnums:      17,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_common_enums_proto_goTypes,
		DependencyIndexes: file_v1_common_enums_proto_depIdxs,
		EnumInfos:         file_v1_common_enums_proto_enumTypes,
	}.Build()
	File_v1_common_enums_proto = out.File
	file_v1_common_enums_proto_goTypes = nil
	file_v1_common_enums_proto_depIdxs = nil
}
