// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/common/error.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason is a machine-readable error enum shared across all services.
// Returned in the error details so clients can branch on a stable reason code
// instead of parsing human-readable messages. In Kratos these map to error
// metadata; each service may add its own reasons but these common ones cover
// the cross-cutting cases.
type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	// Generic / transport
	ErrorReason_ERROR_REASON_VALIDATION_FAILED ErrorReason = 1 // request failed field validation
	ErrorReason_ERROR_REASON_NOT_FOUND         ErrorReason = 2 // entity does not exist
	ErrorReason_ERROR_REASON_ALREADY_EXISTS    ErrorReason = 3 // unique-constraint conflict
	ErrorReason_ERROR_REASON_PERMISSION_DENIED ErrorReason = 4 // caller not authorised
	ErrorReason_ERROR_REASON_INTERNAL          ErrorReason = 5 // unexpected server error
	// Domain-specific (money / lifecycle)
	ErrorReason_ERROR_REASON_CUSTOMER_NOT_ACTIVE  ErrorReason = 100 // account op on non-active customer
	ErrorReason_ERROR_REASON_ACCOUNT_FROZEN       ErrorReason = 101 // money op on frozen account
	ErrorReason_ERROR_REASON_ACCOUNT_CLOSED       ErrorReason = 102 // money op on closed account
	ErrorReason_ERROR_REASON_INSUFFICIENT_FUNDS   ErrorReason = 103 // debit exceeds balance + overdraft
	ErrorReason_ERROR_REASON_CURRENCY_MISMATCH    ErrorReason = 104 // entries span multiple currencies
	ErrorReason_ERROR_REASON_UNBALANCED_ENTRIES   ErrorReason = 105 // ledger entries do not sum to zero
	ErrorReason_ERROR_REASON_ILLEGAL_TRANSITION   ErrorReason = 106 // invalid status state-machine move
	ErrorReason_ERROR_REASON_IDEMPOTENCY_CONFLICT ErrorReason = 107 // same key, different payload
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:   "ERROR_REASON_UNSPECIFIED",
		1:   "ERROR_REASON_VALIDATION_FAILED",
		2:   "ERROR_REASON_NOT_FOUND",
		3:   "ERROR_REASON_ALREADY_EXISTS",
		4:   "ERROR_REASON_PERMISSION_DENIED",
		5:   "ERROR_REASON_INTERNAL",
		100: "ERROR_REASON_CUSTOMER_NOT_ACTIVE",
		101: "ERROR_REASON_ACCOUNT_FROZEN",
		102: "ERROR_REASON_ACCOUNT_CLOSED",
		103: "ERROR_REASON_INSUFFICIENT_FUNDS",
		104: "ERROR_REASON_CURRENCY_MISMATCH",
		105: "ERROR_REASON_UNBALANCED_ENTRIES",
		106: "ERROR_REASON_ILLEGAL_TRANSITION",
		107: "ERROR_REASON_IDEMPOTENCY_CONFLICT",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":          0,
		"ERROR_REASON_VALIDATION_FAILED":    1,
		"ERROR_REASON_NOT_FOUND":            2,
		"ERROR_REASON_ALREADY_EXISTS":       3,
		"ERROR_REASON_PERMISSION_DENIED":    4,
		"ERROR_REASON_INTERNAL":             5,
		"ERROR_REASON_CUSTOMER_NOT_ACTIVE":  100,
		"ERROR_REASON_ACCOUNT_FROZEN":       101,
		"ERROR_REASON_ACCOUNT_CLOSED":       102,
		"ERROR_REASON_INSUFFICIENT_FUNDS":   103,
		"ERROR_REASON_CURRENCY_MISMATCH":    104,
		"ERROR_REASON_UNBALANCED_ENTRIES":   105,
		"ERROR_REASON_ILLEGAL_TRANSITION":   106,
		"ERROR_REASON_IDEMPOTENCY_CONFLICT": 107,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_v1_common_error_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_error_proto_rawDescGZIP(), []int{0}
}

var File_v1_common_error_proto protoreflect.FileDescriptor

const file_v1_common_error_proto_rawDesc = "" +
	"\n" +
	"\x15v1/common/error.proto\x12\tcommon.v1*\xed\x03\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eERROR_REASON_VALIDATION_FAILED\x10\x01\x12\x1a\n" +
	"\x16ERROR_REASON_NOT_FOUND\x10\x02\x12\x1f\n" +
	"\x1bERROR_REASON_ALREADY_EXISTS\x10\x03\x12\"\n" +
	"\x1eERROR_REASON_PERMISSION_DENIED\x10\x04\x12\x19\n" +
	"\x15ERROR_REASON_INTERNAL\x10\x05\x12$\n" +
	" ERROR_REASON_CUSTOMER_NOT_ACTIVE\x10d\x12\x1f\n" +
	"\x1bERROR_REASON_ACCOUNT_FROZEN\x10e\x12\x1f\n" +
	"\x1bERROR_REASON_ACCOUNT_CLOSED\x10f\x12#\n" +
	"\x1fERROR_REASON_INSUFFICIENT_FUNDS\x10g\x12\"\n" +
	"\x1eERROR_REASON_CURRENCY_MISMATCH\x10h\x12#\n" +
	"\x1fERROR_REASON_UNBALANCED_ENTRIES\x10i\x12#\n" +
	"\x1fERROR_REASON_ILLEGAL_TRANSITION\x10j\x12%\n" +
	"!ERROR_REASON_IDEMPOTENCY_CONFLICT\x10kB7Z5github.com/visvesh-ramesh/corebank/v1/common;commonv1b\x06proto3"

var (
	file_v1_common_error_proto_rawDescOnce sync.Once
	file_v1_common_error_proto_rawDescData []byte
)

func file_v1_common_error_proto_rawDescGZIP() []byte {
	file_v1_common_error_proto_rawDescOnce.Do(func() {
		file_v1_common_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_common_error_proto_rawDesc), len(file_v1_common_error_proto_rawDesc)))
	})
	return file_v1_common_error_proto_rawDescData
}

var file_v1_common_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_common_error_proto_goTypes = []any{
	(ErrorReason)(0), // 0: common.v1.ErrorReason
}
var file_v1_common_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_common_error_proto_init() }
func file_v1_common_error_proto_init() {
	if File_v1_common_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_common_error_proto_rawDesc), len(file_v1_common_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_common_error_proto_goTypes,
		DependencyIndexes: file_v1_common_error_proto_depIdxs,
		EnumInfos:         file_v1_common_error_proto_enumTypes,
	}.Build()
	File_v1_common_error_proto = out.File
	file_v1_common_error_proto_goTypes = nil
	file_v1_common_error_proto_depIdxs = nil
}
