// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBusinessAddress = "business_addresses"

// BusinessAddress mapped from table <business_addresses>
type BusinessAddress struct {
	ID          int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	BusinessID  int64   `gorm:"column:business_id;type:bigint;not null;index:idx_business_addresses_business_id,priority:1" json:"business_id"`
	AddressType int16   `gorm:"column:address_type;type:smallint;not null" json:"address_type"`
	Line1       string  `gorm:"column:line1;type:character varying(255);not null" json:"line1"`
	Line2       *string `gorm:"column:line2;type:character varying(255)" json:"line2"`
	City        string  `gorm:"column:city;type:character varying(100);not null" json:"city"`
	State       string  `gorm:"column:state;type:character varying(100);not null" json:"state"`
	PostalCode  string  `gorm:"column:postal_code;type:character varying(20);not null" json:"postal_code"`
	Country     string  `gorm:"column:country;type:character(2);not null" json:"country"`
	IsPrimary   bool    `gorm:"column:is_primary;type:boolean;not null" json:"is_primary"`
}

// TableName BusinessAddress's table name
func (*BusinessAddress) TableName() string {
	return TableNameBusinessAddress
}
