// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBusinessProprietor = "business_proprietors"

// BusinessProprietor mapped from table <business_proprietors>
type BusinessProprietor struct {
	ID         int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	BusinessID int64   `gorm:"column:business_id;type:bigint;not null;uniqueIndex:idx_proprietors_business_id,priority:1" json:"business_id"`
	FirstName  string  `gorm:"column:first_name;type:character varying(100);not null" json:"first_name"`
	LastName   string  `gorm:"column:last_name;type:character varying(100);not null" json:"last_name"`
	Email      string  `gorm:"column:email;type:character varying(255);not null" json:"email"`
	NationalID *string `gorm:"column:national_id;type:character varying(100)" json:"national_id"`
}

// TableName BusinessProprietor's table name
func (*BusinessProprietor) TableName() string {
	return TableNameBusinessProprietor
}
