// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	ID        string    `gorm:"column:id;type:text;primaryKey" json:"id"`
	Type      string    `gorm:"column:type;type:text;not null" json:"type"`
	FullName  string    `gorm:"column:full_name;type:text;not null" json:"full_name"`
	Email     string    `gorm:"column:email;type:text;not null;index:idx_customers_email,priority:1" json:"email"`
	Phone     string    `gorm:"column:phone;type:text;not null" json:"phone"`
	KycStatus string    `gorm:"column:kyc_status;type:text;not null;index:idx_customers_kyc_status,priority:1;default:PENDING" json:"kyc_status"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
