// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProprietorPhone = "proprietor_phones"

// ProprietorPhone mapped from table <proprietor_phones>
type ProprietorPhone struct {
	ID           int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ProprietorID int64  `gorm:"column:proprietor_id;type:bigint;not null;index:idx_proprietor_phones_proprietor_id,priority:1" json:"proprietor_id"`
	PhoneType    int16  `gorm:"column:phone_type;type:smallint;not null" json:"phone_type"`
	CountryCode  string `gorm:"column:country_code;type:character varying(8);not null" json:"country_code"`
	Number       string `gorm:"column:number;type:character varying(30);not null" json:"number"`
	IsPrimary    bool   `gorm:"column:is_primary;type:boolean;not null" json:"is_primary"`
}

// TableName ProprietorPhone's table name
func (*ProprietorPhone) TableName() string {
	return TableNameProprietorPhone
}
