// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"account/internal/conf"
	"account/internal/data"
	"account/internal/handler"
	"account/internal/server"
	"account/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confClients *conf.ClientConf, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	accountRepo := data.NewAccountRepo(dataData)
	customerClient, cleanup2, err := data.NewCustomerGRPCClient(confClients)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ledgerClient, cleanup3, err := data.NewLedgerGRPCClient(confClients)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	accountHandler := handler.NewAccountHandler(accountRepo, customerClient, ledgerClient)
	accountService := service.NewAccountService(accountHandler)
	grpcServer := server.NewGRPCServer(confServer, accountService, logger)
	httpServer := server.NewHTTPServer(confServer, accountService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
