server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    host: localhost
    port: 5432
    user: corebank
    password: corebank
    dbname: corebank
    sslmode: disable
    timezone: Asia/Kolkata
