// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/account/account_service.proto

package accountv1

import (
	common "github.com/visvesh-ramesh/corebank/v1/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenAccountRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CustomerId int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Type       common.AccountType     `protobuf:"varint,2,opt,name=type,proto3,enum=common.v1.AccountType" json:"type,omitempty"`
	// ISO-4217 currency code; fixed at open time.
	Currency string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	// Optional overdraft limit (minor units) — only honoured for CURRENT accounts.
	OverdraftLimitMinor int64 `protobuf:"varint,4,opt,name=overdraft_limit_minor,json=overdraftLimitMinor,proto3" json:"overdraft_limit_minor,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OpenAccountRequest) Reset() {
	*x = OpenAccountRequest{}
	mi := &file_v1_account_account_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAccountRequest) ProtoMessage() {}

func (x *OpenAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAccountRequest.ProtoReflect.Descriptor instead.
func (*OpenAccountRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_account_service_proto_rawDescGZIP(), []int{0}
}

func (x *OpenAccountRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *OpenAccountRequest) GetType() common.AccountType {
	if x != nil {
		return x.Type
	}
	return common.AccountType(0)
}

func (x *OpenAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *OpenAccountRequest) GetOverdraftLimitMinor() int64 {
	if x != nil {
		return x.OverdraftLimitMinor
	}
	return 0
}

type OpenAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAccountResponse) Reset() {
	*x = OpenAccountResponse{}
	mi := &file_v1_account_account_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAccountResponse) ProtoMessage() {}

func (x *OpenAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAccountResponse.ProtoReflect.Descriptor instead.
func (*OpenAccountResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_account_service_proto_rawDescGZIP(), []int{1}
}

func (x *OpenAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_v1_account_account_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_account_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_v1_account_account_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_account_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListAccountsByCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Page          *common.PageRequest    `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsByCustomerRequest) Reset() {
	*x = ListAccountsByCustomerRequest{}
	mi := &file_v1_account_account_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsByCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsByCustomerRequest) ProtoMessage() {}

func (x *ListAccountsByCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsByCustomerRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsByCustomerRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_account_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccountsByCustomerRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *ListAccountsByCustomerRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAccountsByCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsByCustomerResponse) Reset() {
	*x = ListAccountsByCustomerResponse{}
	mi := &file_v1_account_account_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsByCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsByCustomerResponse) ProtoMessage() {}

func (x *ListAccountsByCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsByCustomerResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsByCustomerResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_account_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListAccountsByCustomerResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ListAccountsByCustomerResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdateAccountStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewStatus     common.AccountStatus   `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=common.v1.AccountStatus" json:"new_status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountStatusRequest) Reset() {
	*x = UpdateAccountStatusRequest{}
	mi := &file_v1_account_account_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountStatusRequest) ProtoMessage() {}

func (x *UpdateAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_account_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccountStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAccountStatusRequest) GetNewStatus() common.AccountStatus {
	if x != nil {
		return x.NewStatus
	}
	return common.AccountStatus(0)
}

func (x *UpdateAccountStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpdateAccountStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountStatusResponse) Reset() {
	*x = UpdateAccountStatusResponse{}
	mi := &file_v1_account_account_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountStatusResponse) ProtoMessage() {}

func (x *UpdateAccountStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_account_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAccountStatusResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type CloseAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAccountRequest) Reset() {
	*x = CloseAccountRequest{}
	mi := &file_v1_account_account_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAccountRequest) ProtoMessage() {}

func (x *CloseAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAccountRequest.ProtoReflect.Descriptor instead.
func (*CloseAccountRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_account_service_proto_rawDescGZIP(), []int{8}
}

func (x *CloseAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CloseAccountRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CloseAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAccountResponse) Reset() {
	*x = CloseAccountResponse{}
	mi := &file_v1_account_account_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAccountResponse) ProtoMessage() {}

func (x *CloseAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAccountResponse.ProtoReflect.Descriptor instead.
func (*CloseAccountResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_account_service_proto_rawDescGZIP(), []int{9}
}

func (x *CloseAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_v1_account_account_service_proto protoreflect.FileDescriptor

const file_v1_account_account_service_proto_rawDesc = "" +
	"\n" +
	" v1/account/account_service.proto\x12\n" +
	"account.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x18v1/account/account.proto\x1a\x16v1/common/common.proto\x1a\x15v1/common/enums.proto\"\xb1\x01\n" +
	"\x12OpenAccountRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.common.v1.AccountTypeR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x122\n" +
	"\x15overdraft_limit_minor\x18\x04 \x01(\x03R\x13overdraftLimitMinor\"D\n" +
	"\x13OpenAccountResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x12GetAccountResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\"l\n" +
	"\x1dListAccountsByCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.common.v1.PageRequestR\x04page\"~\n" +
	"\x1eListAccountsByCustomerResponse\x12/\n" +
	"\baccounts\x18\x01 \x03(\v2\x13.account.v1.AccountR\baccounts\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page\"}\n" +
	"\x1aUpdateAccountStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x18.common.v1.AccountStatusR\tnewStatus\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"L\n" +
	"\x1bUpdateAccountStatusResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\"=\n" +
	"\x13CloseAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"E\n" +
	"\x14CloseAccountResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount2\x86\x05\n" +
	"\x0eAccountService\x12g\n" +
	"\vOpenAccount\x12\x1e.account.v1.OpenAccountRequest\x1a\x1f.account.v1.OpenAccountResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/accounts\x12f\n" +
	"\n" +
	"GetAccount\x12\x1d.account.v1.GetAccountRequest\x1a\x1e.account.v1.GetAccountResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/accounts/{id}\x12\x9d\x01\n" +
	"\x16ListAccountsByCustomer\x12).account.v1.ListAccountsByCustomerRequest\x1a*.account.v1.ListAccountsByCustomerResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/customers/{customer_id}/accounts\x12\x8b\x01\n" +
	"\x13UpdateAccountStatus\x12&.account.v1.UpdateAccountStatusRequest\x1a'.account.v1.UpdateAccountStatusResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*2\x18/v1/accounts/{id}/status\x12u\n" +
	"\fCloseAccount\x12\x1f.account.v1.CloseAccountRequest\x1a .account.v1.CloseAccountResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/accounts/{id}:closeB9Z7github.com/visvesh-ramesh/corebank/v1/account;accountv1b\x06proto3"

var (
	file_v1_account_account_service_proto_rawDescOnce sync.Once
	file_v1_account_account_service_proto_rawDescData []byte
)

func file_v1_account_account_service_proto_rawDescGZIP() []byte {
	file_v1_account_account_service_proto_rawDescOnce.Do(func() {
		file_v1_account_account_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_account_account_service_proto_rawDesc), len(file_v1_account_account_service_proto_rawDesc)))
	})
	return file_v1_account_account_service_proto_rawDescData
}

var file_v1_account_account_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_account_account_service_proto_goTypes = []any{
	(*OpenAccountRequest)(nil),             // 0: account.v1.OpenAccountRequest
	(*OpenAccountResponse)(nil),            // 1: account.v1.OpenAccountResponse
	(*GetAccountRequest)(nil),              // 2: account.v1.GetAccountRequest
	(*GetAccountResponse)(nil),             // 3: account.v1.GetAccountResponse
	(*ListAccountsByCustomerRequest)(nil),  // 4: account.v1.ListAccountsByCustomerRequest
	(*ListAccountsByCustomerResponse)(nil), // 5: account.v1.ListAccountsByCustomerResponse
	(*UpdateAccountStatusRequest)(nil),     // 6: account.v1.UpdateAccountStatusRequest
	(*UpdateAccountStatusResponse)(nil),    // 7: account.v1.UpdateAccountStatusResponse
	(*CloseAccountRequest)(nil),            // 8: account.v1.CloseAccountRequest
	(*CloseAccountResponse)(nil),           // 9: account.v1.CloseAccountResponse
	(common.AccountType)(0),                // 10: common.v1.AccountType
	(*Account)(nil),                        // 11: account.v1.Account
	(*common.PageRequest)(nil),             // 12: common.v1.PageRequest
	(*common.PageResponse)(nil),            // 13: common.v1.PageResponse
	(common.AccountStatus)(0),              // 14: common.v1.AccountStatus
}
var file_v1_account_account_service_proto_depIdxs = []int32{
	10, // 0: account.v1.OpenAccountRequest.type:type_name -> common.v1.AccountType
	11, // 1: account.v1.OpenAccountResponse.account:type_name -> account.v1.Account
	11, // 2: account.v1.GetAccountResponse.account:type_name -> account.v1.Account
	12, // 3: account.v1.ListAccountsByCustomerRequest.page:type_name -> common.v1.PageRequest
	11, // 4: account.v1.ListAccountsByCustomerResponse.accounts:type_name -> account.v1.Account
	13, // 5: account.v1.ListAccountsByCustomerResponse.page:type_name -> common.v1.PageResponse
	14, // 6: account.v1.UpdateAccountStatusRequest.new_status:type_name -> common.v1.AccountStatus
	11, // 7: account.v1.UpdateAccountStatusResponse.account:type_name -> account.v1.Account
	11, // 8: account.v1.CloseAccountResponse.account:type_name -> account.v1.Account
	0,  // 9: account.v1.AccountService.OpenAccount:input_type -> account.v1.OpenAccountRequest
	2,  // 10: account.v1.AccountService.GetAccount:input_type -> account.v1.GetAccountRequest
	4,  // 11: account.v1.AccountService.ListAccountsByCustomer:input_type -> account.v1.ListAccountsByCustomerRequest
	6,  // 12: account.v1.AccountService.UpdateAccountStatus:input_type -> account.v1.UpdateAccountStatusRequest
	8,  // 13: account.v1.AccountService.CloseAccount:input_type -> account.v1.CloseAccountRequest
	1,  // 14: account.v1.AccountService.OpenAccount:output_type -> account.v1.OpenAccountResponse
	3,  // 15: account.v1.AccountService.GetAccount:output_type -> account.v1.GetAccountResponse
	5,  // 16: account.v1.AccountService.ListAccountsByCustomer:output_type -> account.v1.ListAccountsByCustomerResponse
	7,  // 17: account.v1.AccountService.UpdateAccountStatus:output_type -> account.v1.UpdateAccountStatusResponse
	9,  // 18: account.v1.AccountService.CloseAccount:output_type -> account.v1.CloseAccountResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_v1_account_account_service_proto_init() }
func file_v1_account_account_service_proto_init() {
	if File_v1_account_account_service_proto != nil {
		return
	}
	file_v1_account_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_account_account_service_proto_rawDesc), len(file_v1_account_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_account_account_service_proto_goTypes,
		DependencyIndexes: file_v1_account_account_service_proto_depIdxs,
		MessageInfos:      file_v1_account_account_service_proto_msgTypes,
	}.Build()
	File_v1_account_account_service_proto = out.File
	file_v1_account_account_service_proto_goTypes = nil
	file_v1_account_account_service_proto_depIdxs = nil
}
