// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/account/account.proto

package accountv1

import (
	common "github.com/visvesh-ramesh/corebank/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account belongs to exactly one customer (customer_id) but is owned by the
// Account service. The balance shown here is a CACHED projection — the Ledger
// service is the source of truth. We expose it for convenience and reconcile
// against the ledger on any disagreement (ledger always wins).
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-generated identifier (auto-increment bigint in PostgreSQL).
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Reference into the Customer service — never a cross-DB join.
	CustomerId int64                `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Type       common.AccountType   `protobuf:"varint,3,opt,name=type,proto3,enum=common.v1.AccountType" json:"type,omitempty"`
	Status     common.AccountStatus `protobuf:"varint,4,opt,name=status,proto3,enum=common.v1.AccountStatus" json:"status,omitempty"`
	// ISO-4217 currency code; fixed at open time, never changed.
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// Cached balance projection. Authoritative balance lives in the Ledger.
	CachedBalance *common.Money `protobuf:"bytes,6,opt,name=cached_balance,json=cachedBalance,proto3" json:"cached_balance,omitempty"`
	// Overdraft limit for CURRENT accounts (minor units). 0 for all other types.
	OverdraftLimitMinor int64                  `protobuf:"varint,7,opt,name=overdraft_limit_minor,json=overdraftLimitMinor,proto3" json:"overdraft_limit_minor,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_v1_account_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_v1_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Account) GetType() common.AccountType {
	if x != nil {
		return x.Type
	}
	return common.AccountType(0)
}

func (x *Account) GetStatus() common.AccountStatus {
	if x != nil {
		return x.Status
	}
	return common.AccountStatus(0)
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetCachedBalance() *common.Money {
	if x != nil {
		return x.CachedBalance
	}
	return nil
}

func (x *Account) GetOverdraftLimitMinor() int64 {
	if x != nil {
		return x.OverdraftLimitMinor
	}
	return 0
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_v1_account_account_proto protoreflect.FileDescriptor

const file_v1_account_account_proto_rawDesc = "" +
	"\n" +
	"\x18v1/account/account.proto\x12\n" +
	"account.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16v1/common/common.proto\x1a\x15v1/common/enums.proto\"\x97\x03\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.common.v1.AccountTypeR\x04type\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.common.v1.AccountStatusR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x127\n" +
	"\x0ecached_balance\x18\x06 \x01(\v2\x10.common.v1.MoneyR\rcachedBalance\x122\n" +
	"\x15overdraft_limit_minor\x18\a \x01(\x03R\x13overdraftLimitMinor\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB9Z7github.com/visvesh-ramesh/corebank/v1/account;accountv1b\x06proto3"

var (
	file_v1_account_account_proto_rawDescOnce sync.Once
	file_v1_account_account_proto_rawDescData []byte
)

func file_v1_account_account_proto_rawDescGZIP() []byte {
	file_v1_account_account_proto_rawDescOnce.Do(func() {
		file_v1_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_account_account_proto_rawDesc), len(file_v1_account_account_proto_rawDesc)))
	})
	return file_v1_account_account_proto_rawDescData
}

var file_v1_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_account_account_proto_goTypes = []any{
	(*Account)(nil),               // 0: account.v1.Account
	(common.AccountType)(0),       // 1: common.v1.AccountType
	(common.AccountStatus)(0),     // 2: common.v1.AccountStatus
	(*common.Money)(nil),          // 3: common.v1.Money
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_v1_account_account_proto_depIdxs = []int32{
	1, // 0: account.v1.Account.type:type_name -> common.v1.AccountType
	2, // 1: account.v1.Account.status:type_name -> common.v1.AccountStatus
	3, // 2: account.v1.Account.cached_balance:type_name -> common.v1.Money
	4, // 3: account.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	4, // 4: account.v1.Account.updated_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_account_account_proto_init() }
func file_v1_account_account_proto_init() {
	if File_v1_account_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_account_account_proto_rawDesc), len(file_v1_account_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_account_account_proto_goTypes,
		DependencyIndexes: file_v1_account_account_proto_depIdxs,
		MessageInfos:      file_v1_account_account_proto_msgTypes,
	}.Build()
	File_v1_account_account_proto = out.File
	file_v1_account_account_proto_goTypes = nil
	file_v1_account_account_proto_depIdxs = nil
}
