// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/account/account_service.proto

package accountv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAccountServiceCloseAccount = "/account.v1.AccountService/CloseAccount"
const OperationAccountServiceGetAccount = "/account.v1.AccountService/GetAccount"
const OperationAccountServiceListAccountsByCustomer = "/account.v1.AccountService/ListAccountsByCustomer"
const OperationAccountServiceOpenAccount = "/account.v1.AccountService/OpenAccount"
const OperationAccountServiceUpdateAccountStatus = "/account.v1.AccountService/UpdateAccountStatus"

type AccountServiceHTTPServer interface {
	// CloseAccount CloseAccount moves an account to CLOSED. Rejected unless the
	// authoritative balance (from Ledger) is zero.
	CloseAccount(context.Context, *CloseAccountRequest) (*CloseAccountResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	ListAccountsByCustomer(context.Context, *ListAccountsByCustomerRequest) (*ListAccountsByCustomerResponse, error)
	// OpenAccount OpenAccount creates an account for an existing, active customer.
	// The service calls CustomerService.GetCustomer to validate the customer
	// exists and is ACTIVE before creating (cross-service validation via gRPC).
	OpenAccount(context.Context, *OpenAccountRequest) (*OpenAccountResponse, error)
	// UpdateAccountStatus UpdateAccountStatus transitions an account (activate, freeze, unfreeze).
	// Transition legality is validated server-side against the state machine.
	UpdateAccountStatus(context.Context, *UpdateAccountStatusRequest) (*UpdateAccountStatusResponse, error)
}

func RegisterAccountServiceHTTPServer(s *http.Server, srv AccountServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/accounts", _AccountService_OpenAccount0_HTTP_Handler(srv))
	r.GET("/v1/accounts/{id}", _AccountService_GetAccount0_HTTP_Handler(srv))
	r.GET("/v1/customers/{customer_id}/accounts", _AccountService_ListAccountsByCustomer0_HTTP_Handler(srv))
	r.PATCH("/v1/accounts/{id}/status", _AccountService_UpdateAccountStatus0_HTTP_Handler(srv))
	r.POST("/v1/accounts/{id}:close", _AccountService_CloseAccount0_HTTP_Handler(srv))
}

func _AccountService_OpenAccount0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OpenAccountRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceOpenAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OpenAccount(ctx, req.(*OpenAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OpenAccountResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_GetAccount0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceGetAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAccount(ctx, req.(*GetAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAccountResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_ListAccountsByCustomer0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAccountsByCustomerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceListAccountsByCustomer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAccountsByCustomer(ctx, req.(*ListAccountsByCustomerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAccountsByCustomerResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_UpdateAccountStatus0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAccountStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceUpdateAccountStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAccountStatus(ctx, req.(*UpdateAccountStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateAccountStatusResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_CloseAccount0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CloseAccountRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceCloseAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CloseAccount(ctx, req.(*CloseAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CloseAccountResponse)
		return ctx.Result(200, reply)
	}
}

type AccountServiceHTTPClient interface {
	// CloseAccount CloseAccount moves an account to CLOSED. Rejected unless the
	// authoritative balance (from Ledger) is zero.
	CloseAccount(ctx context.Context, req *CloseAccountRequest, opts ...http.CallOption) (rsp *CloseAccountResponse, err error)
	GetAccount(ctx context.Context, req *GetAccountRequest, opts ...http.CallOption) (rsp *GetAccountResponse, err error)
	ListAccountsByCustomer(ctx context.Context, req *ListAccountsByCustomerRequest, opts ...http.CallOption) (rsp *ListAccountsByCustomerResponse, err error)
	// OpenAccount OpenAccount creates an account for an existing, active customer.
	// The service calls CustomerService.GetCustomer to validate the customer
	// exists and is ACTIVE before creating (cross-service validation via gRPC).
	OpenAccount(ctx context.Context, req *OpenAccountRequest, opts ...http.CallOption) (rsp *OpenAccountResponse, err error)
	// UpdateAccountStatus UpdateAccountStatus transitions an account (activate, freeze, unfreeze).
	// Transition legality is validated server-side against the state machine.
	UpdateAccountStatus(ctx context.Context, req *UpdateAccountStatusRequest, opts ...http.CallOption) (rsp *UpdateAccountStatusResponse, err error)
}

type AccountServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAccountServiceHTTPClient(client *http.Client) AccountServiceHTTPClient {
	return &AccountServiceHTTPClientImpl{client}
}

// CloseAccount CloseAccount moves an account to CLOSED. Rejected unless the
// authoritative balance (from Ledger) is zero.
func (c *AccountServiceHTTPClientImpl) CloseAccount(ctx context.Context, in *CloseAccountRequest, opts ...http.CallOption) (*CloseAccountResponse, error) {
	var out CloseAccountResponse
	pattern := "/v1/accounts/{id}:close"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAccountServiceCloseAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AccountServiceHTTPClientImpl) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...http.CallOption) (*GetAccountResponse, error) {
	var out GetAccountResponse
	pattern := "/v1/accounts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAccountServiceGetAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AccountServiceHTTPClientImpl) ListAccountsByCustomer(ctx context.Context, in *ListAccountsByCustomerRequest, opts ...http.CallOption) (*ListAccountsByCustomerResponse, error) {
	var out ListAccountsByCustomerResponse
	pattern := "/v1/customers/{customer_id}/accounts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAccountServiceListAccountsByCustomer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// OpenAccount OpenAccount creates an account for an existing, active customer.
// The service calls CustomerService.GetCustomer to validate the customer
// exists and is ACTIVE before creating (cross-service validation via gRPC).
func (c *AccountServiceHTTPClientImpl) OpenAccount(ctx context.Context, in *OpenAccountRequest, opts ...http.CallOption) (*OpenAccountResponse, error) {
	var out OpenAccountResponse
	pattern := "/v1/accounts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAccountServiceOpenAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateAccountStatus UpdateAccountStatus transitions an account (activate, freeze, unfreeze).
// Transition legality is validated server-side against the state machine.
func (c *AccountServiceHTTPClientImpl) UpdateAccountStatus(ctx context.Context, in *UpdateAccountStatusRequest, opts ...http.CallOption) (*UpdateAccountStatusResponse, error) {
	var out UpdateAccountStatusResponse
	pattern := "/v1/accounts/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAccountServiceUpdateAccountStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
