// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameLedgerTransaction = "ledger_transactions"

// LedgerTransaction mapped from table <ledger_transactions>
type LedgerTransaction struct {
	ID                   int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Status               int16      `gorm:"column:status;type:smallint;not null;default:1" json:"status"`
	Description          *string    `gorm:"column:description;type:character varying(500)" json:"description"`
	IdempotencyKey       string     `gorm:"column:idempotency_key;type:character varying(255);not null;uniqueIndex:idx_ledger_transactions_idempotency,priority:1" json:"idempotency_key"`
	ReversesTransactionID *int64    `gorm:"column:reverses_transaction_id;type:bigint" json:"reverses_transaction_id"`
	PostedAt             time.Time  `gorm:"column:posted_at;type:timestamptz;not null;default:now()" json:"posted_at"`
}

func (*LedgerTransaction) TableName() string { return TableNameLedgerTransaction }
