// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLedgerEntry = "ledger_entries"

// LedgerEntry mapped from table <ledger_entries>
type LedgerEntry struct {
	ID            int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	TransactionID int64  `gorm:"column:transaction_id;type:bigint;not null;index:idx_ledger_entries_transaction_id,priority:1" json:"transaction_id"`
	AccountID     int64  `gorm:"column:account_id;type:bigint;not null;index:idx_ledger_entries_account_id,priority:1" json:"account_id"`
	Direction     int16  `gorm:"column:direction;type:smallint;not null" json:"direction"`
	AmountMinor   int64  `gorm:"column:amount_minor;type:bigint;not null" json:"amount_minor"`
	Currency      string `gorm:"column:currency;type:character varying(8);not null" json:"currency"`
}

func (*LedgerEntry) TableName() string { return TableNameLedgerEntry }
