// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"transaction/internal/conf"
	"transaction/internal/data"
	"transaction/internal/handler"
	"transaction/internal/server"
	"transaction/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confClients *conf.ClientConf, confApp *conf.AppConf, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	transactionRepo := data.NewTransactionRepo(dataData)
	accountClient, cleanup2, err := data.NewAccountGRPCClient(confClients)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ledgerClient, cleanup3, err := data.NewLedgerGRPCClient(confClients)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	transactionHandler := handler.NewTransactionHandler(transactionRepo, accountClient, ledgerClient, confApp)
	transactionService := service.NewTransactionService(transactionHandler)
	grpcServer := server.NewGRPCServer(confServer, transactionService, logger)
	httpServer := server.NewHTTPServer(confServer, transactionService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
