// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/product/product.proto

package productv1

import (
	common "github.com/visvesh-ramesh/corebank/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DepositConfig holds the rules for a deposit product. A zero-balance account
// and a salary account differ ONLY in these values — same code, different data.
type DepositConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  common.DepositKind     `protobuf:"varint,1,opt,name=kind,proto3,enum=common.v1.DepositKind" json:"kind,omitempty"`
	// Minimum balance the account must maintain (minor units). 0 for
	// zero-balance / BSBDA products.
	MinBalanceMinor int64 `protobuf:"varint,2,opt,name=min_balance_minor,json=minBalanceMinor,proto3" json:"min_balance_minor,omitempty"`
	// Annual interest rate in basis points (1% = 100 bps). Integer to avoid
	// floats — 350 = 3.5% p.a.
	InterestRateBps int32                     `protobuf:"varint,3,opt,name=interest_rate_bps,json=interestRateBps,proto3" json:"interest_rate_bps,omitempty"`
	InterestCalc    common.InterestCalcMethod `protobuf:"varint,4,opt,name=interest_calc,json=interestCalc,proto3,enum=common.v1.InterestCalcMethod" json:"interest_calc,omitempty"`
	// If true, the product requires a periodic salary credit to stay eligible
	// (the distinguishing rule of a "salary account").
	RequiresSalaryCredit bool `protobuf:"varint,5,opt,name=requires_salary_credit,json=requiresSalaryCredit,proto3" json:"requires_salary_credit,omitempty"`
	// Daily withdrawal cap (minor units). 0 = no limit.
	DailyWithdrawalLimitMinor int64 `protobuf:"varint,6,opt,name=daily_withdrawal_limit_minor,json=dailyWithdrawalLimitMinor,proto3" json:"daily_withdrawal_limit_minor,omitempty"`
	// Below-minimum-balance penalty fee (minor units). 0 = none.
	BelowMinBalanceFeeMinor int64 `protobuf:"varint,7,opt,name=below_min_balance_fee_minor,json=belowMinBalanceFeeMinor,proto3" json:"below_min_balance_fee_minor,omitempty"`
	// For TERM deposits: locked tenure in months. 0 for non-term.
	TermMonths    int32 `protobuf:"varint,8,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositConfig) Reset() {
	*x = DepositConfig{}
	mi := &file_v1_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositConfig) ProtoMessage() {}

func (x *DepositConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositConfig.ProtoReflect.Descriptor instead.
func (*DepositConfig) Descriptor() ([]byte, []int) {
	return file_v1_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *DepositConfig) GetKind() common.DepositKind {
	if x != nil {
		return x.Kind
	}
	return common.DepositKind(0)
}

func (x *DepositConfig) GetMinBalanceMinor() int64 {
	if x != nil {
		return x.MinBalanceMinor
	}
	return 0
}

func (x *DepositConfig) GetInterestRateBps() int32 {
	if x != nil {
		return x.InterestRateBps
	}
	return 0
}

func (x *DepositConfig) GetInterestCalc() common.InterestCalcMethod {
	if x != nil {
		return x.InterestCalc
	}
	return common.InterestCalcMethod(0)
}

func (x *DepositConfig) GetRequiresSalaryCredit() bool {
	if x != nil {
		return x.RequiresSalaryCredit
	}
	return false
}

func (x *DepositConfig) GetDailyWithdrawalLimitMinor() int64 {
	if x != nil {
		return x.DailyWithdrawalLimitMinor
	}
	return 0
}

func (x *DepositConfig) GetBelowMinBalanceFeeMinor() int64 {
	if x != nil {
		return x.BelowMinBalanceFeeMinor
	}
	return 0
}

func (x *DepositConfig) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

// LoanConfig holds the rules for a lending product. Note how little it shares
// with DepositConfig — which is exactly why a oneof (not a shared blob) is the
// right model: each product class carries only the fields that apply to it.
type LoanConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MinPrincipalMinor int64                  `protobuf:"varint,1,opt,name=min_principal_minor,json=minPrincipalMinor,proto3" json:"min_principal_minor,omitempty"`
	MaxPrincipalMinor int64                  `protobuf:"varint,2,opt,name=max_principal_minor,json=maxPrincipalMinor,proto3" json:"max_principal_minor,omitempty"`
	InterestType      common.InterestType    `protobuf:"varint,3,opt,name=interest_type,json=interestType,proto3,enum=common.v1.InterestType" json:"interest_type,omitempty"`
	// For FIXED: the rate in bps. For FLOATING: the spread over the benchmark.
	InterestRateBps    int32                     `protobuf:"varint,4,opt,name=interest_rate_bps,json=interestRateBps,proto3" json:"interest_rate_bps,omitempty"`
	Benchmark          common.RateBenchmark      `protobuf:"varint,5,opt,name=benchmark,proto3,enum=common.v1.RateBenchmark" json:"benchmark,omitempty"` // NONE when FIXED
	MinTenureMonths    int32                     `protobuf:"varint,6,opt,name=min_tenure_months,json=minTenureMonths,proto3" json:"min_tenure_months,omitempty"`
	MaxTenureMonths    int32                     `protobuf:"varint,7,opt,name=max_tenure_months,json=maxTenureMonths,proto3" json:"max_tenure_months,omitempty"`
	Amortization       common.AmortizationMethod `protobuf:"varint,8,opt,name=amortization,proto3,enum=common.v1.AmortizationMethod" json:"amortization,omitempty"`
	CollateralRequired bool                      `protobuf:"varint,9,opt,name=collateral_required,json=collateralRequired,proto3" json:"collateral_required,omitempty"` // true for secured loans
	// Months of payment holiday allowed at the start (e.g. education loans).
	MoratoriumMonths int32 `protobuf:"varint,10,opt,name=moratorium_months,json=moratoriumMonths,proto3" json:"moratorium_months,omitempty"`
	// Penalty rate on overdue EMIs, in bps.
	PenalRateBps  int32 `protobuf:"varint,11,opt,name=penal_rate_bps,json=penalRateBps,proto3" json:"penal_rate_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanConfig) Reset() {
	*x = LoanConfig{}
	mi := &file_v1_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanConfig) ProtoMessage() {}

func (x *LoanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanConfig.ProtoReflect.Descriptor instead.
func (*LoanConfig) Descriptor() ([]byte, []int) {
	return file_v1_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *LoanConfig) GetMinPrincipalMinor() int64 {
	if x != nil {
		return x.MinPrincipalMinor
	}
	return 0
}

func (x *LoanConfig) GetMaxPrincipalMinor() int64 {
	if x != nil {
		return x.MaxPrincipalMinor
	}
	return 0
}

func (x *LoanConfig) GetInterestType() common.InterestType {
	if x != nil {
		return x.InterestType
	}
	return common.InterestType(0)
}

func (x *LoanConfig) GetInterestRateBps() int32 {
	if x != nil {
		return x.InterestRateBps
	}
	return 0
}

func (x *LoanConfig) GetBenchmark() common.RateBenchmark {
	if x != nil {
		return x.Benchmark
	}
	return common.RateBenchmark(0)
}

func (x *LoanConfig) GetMinTenureMonths() int32 {
	if x != nil {
		return x.MinTenureMonths
	}
	return 0
}

func (x *LoanConfig) GetMaxTenureMonths() int32 {
	if x != nil {
		return x.MaxTenureMonths
	}
	return 0
}

func (x *LoanConfig) GetAmortization() common.AmortizationMethod {
	if x != nil {
		return x.Amortization
	}
	return common.AmortizationMethod(0)
}

func (x *LoanConfig) GetCollateralRequired() bool {
	if x != nil {
		return x.CollateralRequired
	}
	return false
}

func (x *LoanConfig) GetMoratoriumMonths() int32 {
	if x != nil {
		return x.MoratoriumMonths
	}
	return 0
}

func (x *LoanConfig) GetPenalRateBps() int32 {
	if x != nil {
		return x.PenalRateBps
	}
	return 0
}

// Product is the bank's product catalog entry.
type Product struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-generated identifier (auto-increment bigint in PostgreSQL).
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Stable short code, e.g. "SAV_SALARY", "LOAN_HOME_FLT".
	// Immutable after creation — safe to store in external systems.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Display name, e.g. "Salary Savings Account".
	Name        string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Class       common.ProductClass  `protobuf:"varint,5,opt,name=class,proto3,enum=common.v1.ProductClass" json:"class,omitempty"`
	Status      common.ProductStatus `protobuf:"varint,6,opt,name=status,proto3,enum=common.v1.ProductStatus" json:"status,omitempty"`
	// Products are single-currency; ISO-4217 code fixed at creation.
	Currency string `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	// Exactly ONE config applies, determined by `class`. A DEPOSIT product
	// carries deposit_config; a LOAN product carries loan_config. The oneof
	// enforces the invariant at the type level — it is impossible to set both.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*Product_DepositConfig
	//	*Product_LoanConfig
	Config        isProduct_Config       `protobuf_oneof:"config"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_v1_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_v1_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetClass() common.ProductClass {
	if x != nil {
		return x.Class
	}
	return common.ProductClass(0)
}

func (x *Product) GetStatus() common.ProductStatus {
	if x != nil {
		return x.Status
	}
	return common.ProductStatus(0)
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetConfig() isProduct_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Product) GetDepositConfig() *DepositConfig {
	if x != nil {
		if x, ok := x.Config.(*Product_DepositConfig); ok {
			return x.DepositConfig
		}
	}
	return nil
}

func (x *Product) GetLoanConfig() *LoanConfig {
	if x != nil {
		if x, ok := x.Config.(*Product_LoanConfig); ok {
			return x.LoanConfig
		}
	}
	return nil
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type isProduct_Config interface {
	isProduct_Config()
}

type Product_DepositConfig struct {
	DepositConfig *DepositConfig `protobuf:"bytes,8,opt,name=deposit_config,json=depositConfig,proto3,oneof"`
}

type Product_LoanConfig struct {
	LoanConfig *LoanConfig `protobuf:"bytes,9,opt,name=loan_config,json=loanConfig,proto3,oneof"`
}

func (*Product_DepositConfig) isProduct_Config() {}

func (*Product_LoanConfig) isProduct_Config() {}

var File_v1_product_product_proto protoreflect.FileDescriptor

const file_v1_product_product_proto_rawDesc = "" +
	"\n" +
	"\x18v1/product/product.proto\x12\n" +
	"product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16v1/common/common.proto\x1a\x15v1/common/enums.proto\"\xad\x03\n" +
	"\rDepositConfig\x12*\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x16.common.v1.DepositKindR\x04kind\x12*\n" +
	"\x11min_balance_minor\x18\x02 \x01(\x03R\x0fminBalanceMinor\x12*\n" +
	"\x11interest_rate_bps\x18\x03 \x01(\x05R\x0finterestRateBps\x12B\n" +
	"\rinterest_calc\x18\x04 \x01(\x0e2\x1d.common.v1.InterestCalcMethodR\finterestCalc\x124\n" +
	"\x16requires_salary_credit\x18\x05 \x01(\bR\x14requiresSalaryCredit\x12?\n" +
	"\x1cdaily_withdrawal_limit_minor\x18\x06 \x01(\x03R\x19dailyWithdrawalLimitMinor\x12<\n" +
	"\x1bbelow_min_balance_fee_minor\x18\a \x01(\x03R\x17belowMinBalanceFeeMinor\x12\x1f\n" +
	"\vterm_months\x18\b \x01(\x05R\n" +
	"termMonths\"\xad\x04\n" +
	"\n" +
	"LoanConfig\x12.\n" +
	"\x13min_principal_minor\x18\x01 \x01(\x03R\x11minPrincipalMinor\x12.\n" +
	"\x13max_principal_minor\x18\x02 \x01(\x03R\x11maxPrincipalMinor\x12<\n" +
	"\rinterest_type\x18\x03 \x01(\x0e2\x17.common.v1.InterestTypeR\finterestType\x12*\n" +
	"\x11interest_rate_bps\x18\x04 \x01(\x05R\x0finterestRateBps\x126\n" +
	"\tbenchmark\x18\x05 \x01(\x0e2\x18.common.v1.RateBenchmarkR\tbenchmark\x12*\n" +
	"\x11min_tenure_months\x18\x06 \x01(\x05R\x0fminTenureMonths\x12*\n" +
	"\x11max_tenure_months\x18\a \x01(\x05R\x0fmaxTenureMonths\x12A\n" +
	"\famortization\x18\b \x01(\x0e2\x1d.common.v1.AmortizationMethodR\famortization\x12/\n" +
	"\x13collateral_required\x18\t \x01(\bR\x12collateralRequired\x12+\n" +
	"\x11moratorium_months\x18\n" +
	" \x01(\x05R\x10moratoriumMonths\x12$\n" +
	"\x0epenal_rate_bps\x18\v \x01(\x05R\fpenalRateBps\"\xdf\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12-\n" +
	"\x05class\x18\x05 \x01(\x0e2\x17.common.v1.ProductClassR\x05class\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.common.v1.ProductStatusR\x06status\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12B\n" +
	"\x0edeposit_config\x18\b \x01(\v2\x19.product.v1.DepositConfigH\x00R\rdepositConfig\x129\n" +
	"\vloan_config\x18\t \x01(\v2\x16.product.v1.LoanConfigH\x00R\n" +
	"loanConfig\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\b\n" +
	"\x06configB9Z7github.com/visvesh-ramesh/corebank/v1/product;productv1b\x06proto3"

var (
	file_v1_product_product_proto_rawDescOnce sync.Once
	file_v1_product_product_proto_rawDescData []byte
)

func file_v1_product_product_proto_rawDescGZIP() []byte {
	file_v1_product_product_proto_rawDescOnce.Do(func() {
		file_v1_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_product_product_proto_rawDesc), len(file_v1_product_product_proto_rawDesc)))
	})
	return file_v1_product_product_proto_rawDescData
}

var file_v1_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_product_product_proto_goTypes = []any{
	(*DepositConfig)(nil),          // 0: product.v1.DepositConfig
	(*LoanConfig)(nil),             // 1: product.v1.LoanConfig
	(*Product)(nil),                // 2: product.v1.Product
	(common.DepositKind)(0),        // 3: common.v1.DepositKind
	(common.InterestCalcMethod)(0), // 4: common.v1.InterestCalcMethod
	(common.InterestType)(0),       // 5: common.v1.InterestType
	(common.RateBenchmark)(0),      // 6: common.v1.RateBenchmark
	(common.AmortizationMethod)(0), // 7: common.v1.AmortizationMethod
	(common.ProductClass)(0),       // 8: common.v1.ProductClass
	(common.ProductStatus)(0),      // 9: common.v1.ProductStatus
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_v1_product_product_proto_depIdxs = []int32{
	3,  // 0: product.v1.DepositConfig.kind:type_name -> common.v1.DepositKind
	4,  // 1: product.v1.DepositConfig.interest_calc:type_name -> common.v1.InterestCalcMethod
	5,  // 2: product.v1.LoanConfig.interest_type:type_name -> common.v1.InterestType
	6,  // 3: product.v1.LoanConfig.benchmark:type_name -> common.v1.RateBenchmark
	7,  // 4: product.v1.LoanConfig.amortization:type_name -> common.v1.AmortizationMethod
	8,  // 5: product.v1.Product.class:type_name -> common.v1.ProductClass
	9,  // 6: product.v1.Product.status:type_name -> common.v1.ProductStatus
	0,  // 7: product.v1.Product.deposit_config:type_name -> product.v1.DepositConfig
	1,  // 8: product.v1.Product.loan_config:type_name -> product.v1.LoanConfig
	10, // 9: product.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	10, // 10: product.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_v1_product_product_proto_init() }
func file_v1_product_product_proto_init() {
	if File_v1_product_product_proto != nil {
		return
	}
	file_v1_product_product_proto_msgTypes[2].OneofWrappers = []any{
		(*Product_DepositConfig)(nil),
		(*Product_LoanConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_product_product_proto_rawDesc), len(file_v1_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_product_product_proto_goTypes,
		DependencyIndexes: file_v1_product_product_proto_depIdxs,
		MessageInfos:      file_v1_product_product_proto_msgTypes,
	}.Build()
	File_v1_product_product_proto = out.File
	file_v1_product_product_proto_goTypes = nil
	file_v1_product_product_proto_depIdxs = nil
}
