// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/product/product_service.proto

package productv1

import (
	common "github.com/visvesh-ramesh/corebank/v1/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateProductRequest carries the full product definition.
// The oneof config must match the class field — mismatch → VALIDATION_FAILED.
type CreateProductRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Code        string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Class       common.ProductClass    `protobuf:"varint,4,opt,name=class,proto3,enum=common.v1.ProductClass" json:"class,omitempty"`
	// ISO-4217 currency code; fixed at creation time.
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// Types that are valid to be assigned to Config:
	//
	//	*CreateProductRequest_DepositConfig
	//	*CreateProductRequest_LoanConfig
	Config        isCreateProductRequest_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_v1_product_product_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_v1_product_product_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetClass() common.ProductClass {
	if x != nil {
		return x.Class
	}
	return common.ProductClass(0)
}

func (x *CreateProductRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateProductRequest) GetConfig() isCreateProductRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateProductRequest) GetDepositConfig() *DepositConfig {
	if x != nil {
		if x, ok := x.Config.(*CreateProductRequest_DepositConfig); ok {
			return x.DepositConfig
		}
	}
	return nil
}

func (x *CreateProductRequest) GetLoanConfig() *LoanConfig {
	if x != nil {
		if x, ok := x.Config.(*CreateProductRequest_LoanConfig); ok {
			return x.LoanConfig
		}
	}
	return nil
}

type isCreateProductRequest_Config interface {
	isCreateProductRequest_Config()
}

type CreateProductRequest_DepositConfig struct {
	DepositConfig *DepositConfig `protobuf:"bytes,6,opt,name=deposit_config,json=depositConfig,proto3,oneof"`
}

type CreateProductRequest_LoanConfig struct {
	LoanConfig *LoanConfig `protobuf:"bytes,7,opt,name=loan_config,json=loanConfig,proto3,oneof"`
}

func (*CreateProductRequest_DepositConfig) isCreateProductRequest_Config() {}

func (*CreateProductRequest_LoanConfig) isCreateProductRequest_Config() {}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_v1_product_product_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_v1_product_product_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_v1_product_product_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_v1_product_product_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_v1_product_product_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_v1_product_product_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewStatus     common.ProductStatus   `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=common.v1.ProductStatus" json:"new_status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStatusRequest) Reset() {
	*x = UpdateProductStatusRequest{}
	mi := &file_v1_product_product_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStatusRequest) ProtoMessage() {}

func (x *UpdateProductStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_product_product_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProductStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductStatusRequest) GetNewStatus() common.ProductStatus {
	if x != nil {
		return x.NewStatus
	}
	return common.ProductStatus(0)
}

func (x *UpdateProductStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpdateProductStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStatusResponse) Reset() {
	*x = UpdateProductStatusResponse{}
	mi := &file_v1_product_product_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStatusResponse) ProtoMessage() {}

func (x *UpdateProductStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_product_product_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductStatusResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassFilter   common.ProductClass    `protobuf:"varint,1,opt,name=class_filter,json=classFilter,proto3,enum=common.v1.ProductClass" json:"class_filter,omitempty"`     // UNSPECIFIED -> all classes
	StatusFilter  common.ProductStatus   `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=common.v1.ProductStatus" json:"status_filter,omitempty"` // UNSPECIFIED -> all statuses
	Page          *common.PageRequest    `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_v1_product_product_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_v1_product_product_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsRequest) GetClassFilter() common.ProductClass {
	if x != nil {
		return x.ClassFilter
	}
	return common.ProductClass(0)
}

func (x *ListProductsRequest) GetStatusFilter() common.ProductStatus {
	if x != nil {
		return x.StatusFilter
	}
	return common.ProductStatus(0)
}

func (x *ListProductsRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_v1_product_product_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_product_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_v1_product_product_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_v1_product_product_service_proto protoreflect.FileDescriptor

const file_v1_product_product_service_proto_rawDesc = "" +
	"\n" +
	" v1/product/product_service.proto\x12\n" +
	"product.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x18v1/product/product.proto\x1a\x16v1/common/common.proto\x1a\x15v1/common/enums.proto\"\xb4\x02\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\x05class\x18\x04 \x01(\x0e2\x17.common.v1.ProductClassR\x05class\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12B\n" +
	"\x0edeposit_config\x18\x06 \x01(\v2\x19.product.v1.DepositConfigH\x00R\rdepositConfig\x129\n" +
	"\vloan_config\x18\a \x01(\v2\x16.product.v1.LoanConfigH\x00R\n" +
	"loanConfigB\b\n" +
	"\x06config\"F\n" +
	"\x15CreateProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x12GetProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"}\n" +
	"\x1aUpdateProductStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x18.common.v1.ProductStatusR\tnewStatus\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"L\n" +
	"\x1bUpdateProductStatusResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"\xbc\x01\n" +
	"\x13ListProductsRequest\x12:\n" +
	"\fclass_filter\x18\x01 \x01(\x0e2\x17.common.v1.ProductClassR\vclassFilter\x12=\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2\x18.common.v1.ProductStatusR\fstatusFilter\x12*\n" +
	"\x04page\x18\x03 \x01(\v2\x16.common.v1.PageRequestR\x04page\"t\n" +
	"\x14ListProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page2\xde\x03\n" +
	"\x0eProductService\x12m\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a!.product.v1.CreateProductResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/products\x12f\n" +
	"\n" +
	"GetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x1e.product.v1.GetProductResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/products/{id}\x12\x8b\x01\n" +
	"\x13UpdateProductStatus\x12&.product.v1.UpdateProductStatusRequest\x1a'.product.v1.UpdateProductStatusResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*2\x18/v1/products/{id}/status\x12g\n" +
	"\fListProducts\x12\x1f.product.v1.ListProductsRequest\x1a .product.v1.ListProductsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/productsB9Z7github.com/visvesh-ramesh/corebank/v1/product;productv1b\x06proto3"

var (
	file_v1_product_product_service_proto_rawDescOnce sync.Once
	file_v1_product_product_service_proto_rawDescData []byte
)

func file_v1_product_product_service_proto_rawDescGZIP() []byte {
	file_v1_product_product_service_proto_rawDescOnce.Do(func() {
		file_v1_product_product_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_product_product_service_proto_rawDesc), len(file_v1_product_product_service_proto_rawDesc)))
	})
	return file_v1_product_product_service_proto_rawDescData
}

var file_v1_product_product_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_product_product_service_proto_goTypes = []any{
	(*CreateProductRequest)(nil),        // 0: product.v1.CreateProductRequest
	(*CreateProductResponse)(nil),       // 1: product.v1.CreateProductResponse
	(*GetProductRequest)(nil),           // 2: product.v1.GetProductRequest
	(*GetProductResponse)(nil),          // 3: product.v1.GetProductResponse
	(*UpdateProductStatusRequest)(nil),  // 4: product.v1.UpdateProductStatusRequest
	(*UpdateProductStatusResponse)(nil), // 5: product.v1.UpdateProductStatusResponse
	(*ListProductsRequest)(nil),         // 6: product.v1.ListProductsRequest
	(*ListProductsResponse)(nil),        // 7: product.v1.ListProductsResponse
	(common.ProductClass)(0),            // 8: common.v1.ProductClass
	(*DepositConfig)(nil),               // 9: product.v1.DepositConfig
	(*LoanConfig)(nil),                  // 10: product.v1.LoanConfig
	(*Product)(nil),                     // 11: product.v1.Product
	(common.ProductStatus)(0),           // 12: common.v1.ProductStatus
	(*common.PageRequest)(nil),          // 13: common.v1.PageRequest
	(*common.PageResponse)(nil),         // 14: common.v1.PageResponse
}
var file_v1_product_product_service_proto_depIdxs = []int32{
	8,  // 0: product.v1.CreateProductRequest.class:type_name -> common.v1.ProductClass
	9,  // 1: product.v1.CreateProductRequest.deposit_config:type_name -> product.v1.DepositConfig
	10, // 2: product.v1.CreateProductRequest.loan_config:type_name -> product.v1.LoanConfig
	11, // 3: product.v1.CreateProductResponse.product:type_name -> product.v1.Product
	11, // 4: product.v1.GetProductResponse.product:type_name -> product.v1.Product
	12, // 5: product.v1.UpdateProductStatusRequest.new_status:type_name -> common.v1.ProductStatus
	11, // 6: product.v1.UpdateProductStatusResponse.product:type_name -> product.v1.Product
	8,  // 7: product.v1.ListProductsRequest.class_filter:type_name -> common.v1.ProductClass
	12, // 8: product.v1.ListProductsRequest.status_filter:type_name -> common.v1.ProductStatus
	13, // 9: product.v1.ListProductsRequest.page:type_name -> common.v1.PageRequest
	11, // 10: product.v1.ListProductsResponse.products:type_name -> product.v1.Product
	14, // 11: product.v1.ListProductsResponse.page:type_name -> common.v1.PageResponse
	0,  // 12: product.v1.ProductService.CreateProduct:input_type -> product.v1.CreateProductRequest
	2,  // 13: product.v1.ProductService.GetProduct:input_type -> product.v1.GetProductRequest
	4,  // 14: product.v1.ProductService.UpdateProductStatus:input_type -> product.v1.UpdateProductStatusRequest
	6,  // 15: product.v1.ProductService.ListProducts:input_type -> product.v1.ListProductsRequest
	1,  // 16: product.v1.ProductService.CreateProduct:output_type -> product.v1.CreateProductResponse
	3,  // 17: product.v1.ProductService.GetProduct:output_type -> product.v1.GetProductResponse
	5,  // 18: product.v1.ProductService.UpdateProductStatus:output_type -> product.v1.UpdateProductStatusResponse
	7,  // 19: product.v1.ProductService.ListProducts:output_type -> product.v1.ListProductsResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_product_product_service_proto_init() }
func file_v1_product_product_service_proto_init() {
	if File_v1_product_product_service_proto != nil {
		return
	}
	file_v1_product_product_proto_init()
	file_v1_product_product_service_proto_msgTypes[0].OneofWrappers = []any{
		(*CreateProductRequest_DepositConfig)(nil),
		(*CreateProductRequest_LoanConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_product_product_service_proto_rawDesc), len(file_v1_product_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_product_product_service_proto_goTypes,
		DependencyIndexes: file_v1_product_product_service_proto_depIdxs,
		MessageInfos:      file_v1_product_product_service_proto_msgTypes,
	}.Build()
	File_v1_product_product_service_proto = out.File
	file_v1_product_product_service_proto_goTypes = nil
	file_v1_product_product_service_proto_depIdxs = nil
}
