// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/product/product_service.proto

package productv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProductServiceCreateProduct = "/product.v1.ProductService/CreateProduct"
const OperationProductServiceGetProduct = "/product.v1.ProductService/GetProduct"
const OperationProductServiceListProducts = "/product.v1.ProductService/ListProducts"
const OperationProductServiceUpdateProductStatus = "/product.v1.ProductService/UpdateProductStatus"

type ProductServiceHTTPServer interface {
	// CreateProduct CreateProduct adds a new product to the catalog in DRAFT status. The
	// server validates that the config matches the class (a DEPOSIT product must
	// carry deposit_config, a LOAN product loan_config).
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	// ListProducts ListProducts returns the catalog, optionally filtered by class and/or
	// status (e.g. "all ACTIVE DEPOSIT products" for an account-opening UI).
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	// UpdateProductStatus UpdateProductStatus moves a product through DRAFT -> ACTIVE -> RETIRED.
	// Retiring a product stops new accounts but leaves existing ones running.
	UpdateProductStatus(context.Context, *UpdateProductStatusRequest) (*UpdateProductStatusResponse, error)
}

func RegisterProductServiceHTTPServer(s *http.Server, srv ProductServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/products", _ProductService_CreateProduct0_HTTP_Handler(srv))
	r.GET("/v1/products/{id}", _ProductService_GetProduct0_HTTP_Handler(srv))
	r.PATCH("/v1/products/{id}/status", _ProductService_UpdateProductStatus0_HTTP_Handler(srv))
	r.GET("/v1/products", _ProductService_ListProducts0_HTTP_Handler(srv))
}

func _ProductService_CreateProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceCreateProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProduct(ctx, req.(*CreateProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_GetProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceGetProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProduct(ctx, req.(*GetProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_UpdateProductStatus0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProductStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceUpdateProductStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProductStatus(ctx, req.(*UpdateProductStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateProductStatusResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_ListProducts0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceListProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProducts(ctx, req.(*ListProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsResponse)
		return ctx.Result(200, reply)
	}
}

type ProductServiceHTTPClient interface {
	// CreateProduct CreateProduct adds a new product to the catalog in DRAFT status. The
	// server validates that the config matches the class (a DEPOSIT product must
	// carry deposit_config, a LOAN product loan_config).
	CreateProduct(ctx context.Context, req *CreateProductRequest, opts ...http.CallOption) (rsp *CreateProductResponse, err error)
	GetProduct(ctx context.Context, req *GetProductRequest, opts ...http.CallOption) (rsp *GetProductResponse, err error)
	// ListProducts ListProducts returns the catalog, optionally filtered by class and/or
	// status (e.g. "all ACTIVE DEPOSIT products" for an account-opening UI).
	ListProducts(ctx context.Context, req *ListProductsRequest, opts ...http.CallOption) (rsp *ListProductsResponse, err error)
	// UpdateProductStatus UpdateProductStatus moves a product through DRAFT -> ACTIVE -> RETIRED.
	// Retiring a product stops new accounts but leaves existing ones running.
	UpdateProductStatus(ctx context.Context, req *UpdateProductStatusRequest, opts ...http.CallOption) (rsp *UpdateProductStatusResponse, err error)
}

type ProductServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProductServiceHTTPClient(client *http.Client) ProductServiceHTTPClient {
	return &ProductServiceHTTPClientImpl{client}
}

// CreateProduct CreateProduct adds a new product to the catalog in DRAFT status. The
// server validates that the config matches the class (a DEPOSIT product must
// carry deposit_config, a LOAN product loan_config).
func (c *ProductServiceHTTPClientImpl) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...http.CallOption) (*CreateProductResponse, error) {
	var out CreateProductResponse
	pattern := "/v1/products"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductServiceCreateProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) GetProduct(ctx context.Context, in *GetProductRequest, opts ...http.CallOption) (*GetProductResponse, error) {
	var out GetProductResponse
	pattern := "/v1/products/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductServiceGetProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListProducts ListProducts returns the catalog, optionally filtered by class and/or
// status (e.g. "all ACTIVE DEPOSIT products" for an account-opening UI).
func (c *ProductServiceHTTPClientImpl) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...http.CallOption) (*ListProductsResponse, error) {
	var out ListProductsResponse
	pattern := "/v1/products"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductServiceListProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateProductStatus UpdateProductStatus moves a product through DRAFT -> ACTIVE -> RETIRED.
// Retiring a product stops new accounts but leaves existing ones running.
func (c *ProductServiceHTTPClientImpl) UpdateProductStatus(ctx context.Context, in *UpdateProductStatusRequest, opts ...http.CallOption) (*UpdateProductStatusResponse, error) {
	var out UpdateProductStatusResponse
	pattern := "/v1/products/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductServiceUpdateProductStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
