// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ledger/internal/conf"
	"ledger/internal/data"
	"ledger/internal/handler"
	"ledger/internal/server"
	"ledger/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	ledgerRepo := data.NewLedgerRepo(dataData)
	ledgerHandler := handler.NewLedgerHandler(ledgerRepo)
	ledgerService := service.NewLedgerService(ledgerHandler)
	grpcServer := server.NewGRPCServer(confServer, ledgerService, logger)
	httpServer := server.NewHTTPServer(confServer, ledgerService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
