// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCustomerStatusHistory = "customer_status_history"

// CustomerStatusHistory mapped from table <customer_status_history>
type CustomerStatusHistory struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	CustomerID string    `gorm:"column:customer_id;not null" json:"customer_id"`
	FromStatus string    `gorm:"column:from_status;not null" json:"from_status"`
	ToStatus   string    `gorm:"column:to_status;not null" json:"to_status"`
	Reason     string    `gorm:"column:reason;not null" json:"reason"`
	ChangedAt  time.Time `gorm:"column:changed_at;not null;default:now()" json:"changed_at"`
}

// TableName CustomerStatusHistory's table name
func (*CustomerStatusHistory) TableName() string {
	return TableNameCustomerStatusHistory
}
