// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Type      string    `gorm:"column:type;not null" json:"type"`
	FullName  string    `gorm:"column:full_name;not null" json:"full_name"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	Phone     string    `gorm:"column:phone;not null" json:"phone"`
	KycStatus string    `gorm:"column:kyc_status;not null;default:PENDING" json:"kyc_status"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
