// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/ledger/ledger_service.proto

package ledgerv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLedgerServiceGetBalance = "/ledger.v1.LedgerService/GetBalance"
const OperationLedgerServiceGetTransaction = "/ledger.v1.LedgerService/GetTransaction"
const OperationLedgerServicePostTransaction = "/ledger.v1.LedgerService/PostTransaction"
const OperationLedgerServiceReverseTransaction = "/ledger.v1.LedgerService/ReverseTransaction"

type LedgerServiceHTTPServer interface {
	// GetBalance GetBalance returns the authoritative balance for an account.
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	// PostTransaction PostTransaction atomically applies a balanced set of entries.
	// Validation order (all-or-nothing):
	//   1. entries sum to zero (double-entry invariant)
	//   2. all entries share one currency
	//   3. no account is FROZEN or CLOSED
	//   4. debited accounts have sufficient funds (respecting overdraft limit)
	// Any failure → nothing is written, status = REJECTED.
	//
	// Idempotent: re-posting the same idempotency_key returns the original
	// transaction rather than applying it twice.
	PostTransaction(context.Context, *PostTransactionRequest) (*PostTransactionResponse, error)
	// ReverseTransaction ReverseTransaction posts a NEW transaction with the opposite entries of
	// an existing one. The original is never modified — the reversal is itself
	// an auditable record.
	ReverseTransaction(context.Context, *ReverseTransactionRequest) (*ReverseTransactionResponse, error)
}

func RegisterLedgerServiceHTTPServer(s *http.Server, srv LedgerServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/ledger/transactions", _LedgerService_PostTransaction0_HTTP_Handler(srv))
	r.POST("/v1/ledger/transactions/{transaction_id}:reverse", _LedgerService_ReverseTransaction0_HTTP_Handler(srv))
	r.GET("/v1/ledger/transactions/{transaction_id}", _LedgerService_GetTransaction0_HTTP_Handler(srv))
	r.GET("/v1/ledger/accounts/{account_id}/balance", _LedgerService_GetBalance0_HTTP_Handler(srv))
}

func _LedgerService_PostTransaction0_HTTP_Handler(srv LedgerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PostTransactionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLedgerServicePostTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PostTransaction(ctx, req.(*PostTransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PostTransactionResponse)
		return ctx.Result(200, reply)
	}
}

func _LedgerService_ReverseTransaction0_HTTP_Handler(srv LedgerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReverseTransactionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLedgerServiceReverseTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReverseTransaction(ctx, req.(*ReverseTransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReverseTransactionResponse)
		return ctx.Result(200, reply)
	}
}

func _LedgerService_GetTransaction0_HTTP_Handler(srv LedgerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTransactionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLedgerServiceGetTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTransaction(ctx, req.(*GetTransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTransactionResponse)
		return ctx.Result(200, reply)
	}
}

func _LedgerService_GetBalance0_HTTP_Handler(srv LedgerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBalanceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLedgerServiceGetBalance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBalance(ctx, req.(*GetBalanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBalanceResponse)
		return ctx.Result(200, reply)
	}
}

type LedgerServiceHTTPClient interface {
	// GetBalance GetBalance returns the authoritative balance for an account.
	GetBalance(ctx context.Context, req *GetBalanceRequest, opts ...http.CallOption) (rsp *GetBalanceResponse, err error)
	GetTransaction(ctx context.Context, req *GetTransactionRequest, opts ...http.CallOption) (rsp *GetTransactionResponse, err error)
	// PostTransaction PostTransaction atomically applies a balanced set of entries.
	// Validation order (all-or-nothing):
	//   1. entries sum to zero (double-entry invariant)
	//   2. all entries share one currency
	//   3. no account is FROZEN or CLOSED
	//   4. debited accounts have sufficient funds (respecting overdraft limit)
	// Any failure → nothing is written, status = REJECTED.
	//
	// Idempotent: re-posting the same idempotency_key returns the original
	// transaction rather than applying it twice.
	PostTransaction(ctx context.Context, req *PostTransactionRequest, opts ...http.CallOption) (rsp *PostTransactionResponse, err error)
	// ReverseTransaction ReverseTransaction posts a NEW transaction with the opposite entries of
	// an existing one. The original is never modified — the reversal is itself
	// an auditable record.
	ReverseTransaction(ctx context.Context, req *ReverseTransactionRequest, opts ...http.CallOption) (rsp *ReverseTransactionResponse, err error)
}

type LedgerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLedgerServiceHTTPClient(client *http.Client) LedgerServiceHTTPClient {
	return &LedgerServiceHTTPClientImpl{client}
}

// GetBalance GetBalance returns the authoritative balance for an account.
func (c *LedgerServiceHTTPClientImpl) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...http.CallOption) (*GetBalanceResponse, error) {
	var out GetBalanceResponse
	pattern := "/v1/ledger/accounts/{account_id}/balance"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLedgerServiceGetBalance))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LedgerServiceHTTPClientImpl) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...http.CallOption) (*GetTransactionResponse, error) {
	var out GetTransactionResponse
	pattern := "/v1/ledger/transactions/{transaction_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLedgerServiceGetTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PostTransaction PostTransaction atomically applies a balanced set of entries.
// Validation order (all-or-nothing):
//   1. entries sum to zero (double-entry invariant)
//   2. all entries share one currency
//   3. no account is FROZEN or CLOSED
//   4. debited accounts have sufficient funds (respecting overdraft limit)
// Any failure → nothing is written, status = REJECTED.
//
// Idempotent: re-posting the same idempotency_key returns the original
// transaction rather than applying it twice.
func (c *LedgerServiceHTTPClientImpl) PostTransaction(ctx context.Context, in *PostTransactionRequest, opts ...http.CallOption) (*PostTransactionResponse, error) {
	var out PostTransactionResponse
	pattern := "/v1/ledger/transactions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLedgerServicePostTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReverseTransaction ReverseTransaction posts a NEW transaction with the opposite entries of
// an existing one. The original is never modified — the reversal is itself
// an auditable record.
func (c *LedgerServiceHTTPClientImpl) ReverseTransaction(ctx context.Context, in *ReverseTransactionRequest, opts ...http.CallOption) (*ReverseTransactionResponse, error) {
	var out ReverseTransactionResponse
	pattern := "/v1/ledger/transactions/{transaction_id}:reverse"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLedgerServiceReverseTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
