// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/ledger/ledger.proto

package ledgerv1

import (
	common "github.com/visvesh-ramesh/corebank/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entry is one leg of a ledger transaction: a signed movement against one
// account. Entries are IMMUTABLE once posted — there is no update or delete.
// A mistake is corrected by posting a new, reversing transaction, preserving
// the full audit history.
type Entry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // server-generated
	AccountId int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // which account this leg affects
	Direction common.EntryDirection  `protobuf:"varint,3,opt,name=direction,proto3,enum=common.v1.EntryDirection" json:"direction,omitempty"`
	// Always positive; the direction carries the sign. Minor units only.
	AmountMinor   int64  `protobuf:"varint,4,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_v1_ledger_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entry) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Entry) GetDirection() common.EntryDirection {
	if x != nil {
		return x.Direction
	}
	return common.EntryDirection(0)
}

func (x *Entry) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Entry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// LedgerTransaction is the atomic unit of the ledger: a set of entries that
// together sum to zero. This is the source of truth for all money movement.
type LedgerTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The entries (legs). At least two required; signed amounts must net to zero.
	Entries []*Entry                       `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	Status  common.LedgerTransactionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=common.v1.LedgerTransactionStatus" json:"status,omitempty"`
	// Human-readable description or rejection reason.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Idempotency key: re-posting with the same key returns the original result.
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Non-zero when this transaction reverses another; zero otherwise.
	// proto3 default (0) signals "not a reversal".
	ReversesTransactionId *int64                 `protobuf:"varint,6,opt,name=reverses_transaction_id,json=reversesTransactionId,proto3,oneof" json:"reverses_transaction_id,omitempty"`
	PostedAt              *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LedgerTransaction) Reset() {
	*x = LedgerTransaction{}
	mi := &file_v1_ledger_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerTransaction) ProtoMessage() {}

func (x *LedgerTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerTransaction.ProtoReflect.Descriptor instead.
func (*LedgerTransaction) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *LedgerTransaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerTransaction) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LedgerTransaction) GetStatus() common.LedgerTransactionStatus {
	if x != nil {
		return x.Status
	}
	return common.LedgerTransactionStatus(0)
}

func (x *LedgerTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LedgerTransaction) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *LedgerTransaction) GetReversesTransactionId() int64 {
	if x != nil && x.ReversesTransactionId != nil {
		return *x.ReversesTransactionId
	}
	return 0
}

func (x *LedgerTransaction) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

// Balance is the authoritative balance of an account, derived from the sum of
// all its posted entries. The Account service caches a copy; this is the truth.
type Balance struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance   *common.Money          `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	// Timestamp of the most recent entry included in this calculation.
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_v1_ledger_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *Balance) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Balance) GetBalance() *common.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *Balance) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

var File_v1_ledger_ledger_proto protoreflect.FileDescriptor

const file_v1_ledger_ledger_proto_rawDesc = "" +
	"\n" +
	"\x16v1/ledger/ledger.proto\x12\tledger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16v1/common/common.proto\x1a\x15v1/common/enums.proto\"\xae\x01\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x127\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x19.common.v1.EntryDirectionR\tdirection\x12!\n" +
	"\famount_minor\x18\x04 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\xe8\x02\n" +
	"\x11LedgerTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\aentries\x18\x02 \x03(\v2\x10.ledger.v1.EntryR\aentries\x12:\n" +
	"\x06status\x18\x03 \x01(\x0e2\".common.v1.LedgerTransactionStatusR\x06status\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12;\n" +
	"\x17reverses_transaction_id\x18\x06 \x01(\x03H\x00R\x15reversesTransactionId\x88\x01\x01\x127\n" +
	"\tposted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAtB\x1a\n" +
	"\x18_reverses_transaction_id\"\x85\x01\n" +
	"\aBalance\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12*\n" +
	"\abalance\x18\x02 \x01(\v2\x10.common.v1.MoneyR\abalance\x12/\n" +
	"\x05as_of\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOfB7Z5github.com/visvesh-ramesh/corebank/v1/ledger;ledgerv1b\x06proto3"

var (
	file_v1_ledger_ledger_proto_rawDescOnce sync.Once
	file_v1_ledger_ledger_proto_rawDescData []byte
)

func file_v1_ledger_ledger_proto_rawDescGZIP() []byte {
	file_v1_ledger_ledger_proto_rawDescOnce.Do(func() {
		file_v1_ledger_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_ledger_ledger_proto_rawDesc), len(file_v1_ledger_ledger_proto_rawDesc)))
	})
	return file_v1_ledger_ledger_proto_rawDescData
}

var file_v1_ledger_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_ledger_ledger_proto_goTypes = []any{
	(*Entry)(nil),                       // 0: ledger.v1.Entry
	(*LedgerTransaction)(nil),           // 1: ledger.v1.LedgerTransaction
	(*Balance)(nil),                     // 2: ledger.v1.Balance
	(common.EntryDirection)(0),          // 3: common.v1.EntryDirection
	(common.LedgerTransactionStatus)(0), // 4: common.v1.LedgerTransactionStatus
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
	(*common.Money)(nil),                // 6: common.v1.Money
}
var file_v1_ledger_ledger_proto_depIdxs = []int32{
	3, // 0: ledger.v1.Entry.direction:type_name -> common.v1.EntryDirection
	0, // 1: ledger.v1.LedgerTransaction.entries:type_name -> ledger.v1.Entry
	4, // 2: ledger.v1.LedgerTransaction.status:type_name -> common.v1.LedgerTransactionStatus
	5, // 3: ledger.v1.LedgerTransaction.posted_at:type_name -> google.protobuf.Timestamp
	6, // 4: ledger.v1.Balance.balance:type_name -> common.v1.Money
	5, // 5: ledger.v1.Balance.as_of:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_v1_ledger_ledger_proto_init() }
func file_v1_ledger_ledger_proto_init() {
	if File_v1_ledger_ledger_proto != nil {
		return
	}
	file_v1_ledger_ledger_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_ledger_ledger_proto_rawDesc), len(file_v1_ledger_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_ledger_ledger_proto_goTypes,
		DependencyIndexes: file_v1_ledger_ledger_proto_depIdxs,
		MessageInfos:      file_v1_ledger_ledger_proto_msgTypes,
	}.Build()
	File_v1_ledger_ledger_proto = out.File
	file_v1_ledger_ledger_proto_goTypes = nil
	file_v1_ledger_ledger_proto_depIdxs = nil
}
