// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/ledger/ledger_service.proto

package ledgerv1

import (
	_ "github.com/visvesh-ramesh/corebank/v1/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The legs of the transaction. Signed amounts (via direction) must net zero.
	Entries        []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	IdempotencyKey string   `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Description    string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostTransactionRequest) Reset() {
	*x = PostTransactionRequest{}
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTransactionRequest) ProtoMessage() {}

func (x *PostTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTransactionRequest.ProtoReflect.Descriptor instead.
func (*PostTransactionRequest) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_service_proto_rawDescGZIP(), []int{0}
}

func (x *PostTransactionRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *PostTransactionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PostTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PostTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *LedgerTransaction     `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTransactionResponse) Reset() {
	*x = PostTransactionResponse{}
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTransactionResponse) ProtoMessage() {}

func (x *PostTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTransactionResponse.ProtoReflect.Descriptor instead.
func (*PostTransactionResponse) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_service_proto_rawDescGZIP(), []int{1}
}

func (x *PostTransactionResponse) GetTransaction() *LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ReverseTransactionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionId  int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReverseTransactionRequest) Reset() {
	*x = ReverseTransactionRequest{}
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseTransactionRequest) ProtoMessage() {}

func (x *ReverseTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseTransactionRequest.ProtoReflect.Descriptor instead.
func (*ReverseTransactionRequest) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReverseTransactionRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *ReverseTransactionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReverseTransactionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReverseTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *LedgerTransaction     `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"` // the new reversing transaction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseTransactionResponse) Reset() {
	*x = ReverseTransactionResponse{}
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseTransactionResponse) ProtoMessage() {}

func (x *ReverseTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseTransactionResponse.ProtoReflect.Descriptor instead.
func (*ReverseTransactionResponse) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReverseTransactionResponse) GetTransaction() *LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *LedgerTransaction     `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionResponse) GetTransaction() *LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetBalanceRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ledger_ledger_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_v1_ledger_ledger_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetBalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

var File_v1_ledger_ledger_service_proto protoreflect.FileDescriptor

const file_v1_ledger_ledger_service_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/ledger/ledger_service.proto\x12\tledger.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x16v1/ledger/ledger.proto\x1a\x16v1/common/common.proto\"\x8f\x01\n" +
	"\x16PostTransactionRequest\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.ledger.v1.EntryR\aentries\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"Y\n" +
	"\x17PostTransactionResponse\x12>\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1c.ledger.v1.LedgerTransactionR\vtransaction\"\x83\x01\n" +
	"\x19ReverseTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\\\n" +
	"\x1aReverseTransactionResponse\x12>\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1c.ledger.v1.LedgerTransactionR\vtransaction\">\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\"X\n" +
	"\x16GetTransactionResponse\x12>\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1c.ledger.v1.LedgerTransactionR\vtransaction\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\"B\n" +
	"\x12GetBalanceResponse\x12,\n" +
	"\abalance\x18\x01 \x01(\v2\x12.ledger.v1.BalanceR\abalance2\xb5\x04\n" +
	"\rLedgerService\x12|\n" +
	"\x0fPostTransaction\x12!.ledger.v1.PostTransactionRequest\x1a\".ledger.v1.PostTransactionResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/ledger/transactions\x12\x9e\x01\n" +
	"\x12ReverseTransaction\x12$.ledger.v1.ReverseTransactionRequest\x1a%.ledger.v1.ReverseTransactionResponse\";\x82\xd3\xe4\x93\x025:\x01*\"0/v1/ledger/transactions/{transaction_id}:reverse\x12\x87\x01\n" +
	"\x0eGetTransaction\x12 .ledger.v1.GetTransactionRequest\x1a!.ledger.v1.GetTransactionResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/ledger/transactions/{transaction_id}\x12{\n" +
	"\n" +
	"GetBalance\x12\x1c.ledger.v1.GetBalanceRequest\x1a\x1d.ledger.v1.GetBalanceResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/ledger/accounts/{account_id}/balanceB7Z5github.com/visvesh-ramesh/corebank/v1/ledger;ledgerv1b\x06proto3"

var (
	file_v1_ledger_ledger_service_proto_rawDescOnce sync.Once
	file_v1_ledger_ledger_service_proto_rawDescData []byte
)

func file_v1_ledger_ledger_service_proto_rawDescGZIP() []byte {
	file_v1_ledger_ledger_service_proto_rawDescOnce.Do(func() {
		file_v1_ledger_ledger_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_ledger_ledger_service_proto_rawDesc), len(file_v1_ledger_ledger_service_proto_rawDesc)))
	})
	return file_v1_ledger_ledger_service_proto_rawDescData
}

var file_v1_ledger_ledger_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_ledger_ledger_service_proto_goTypes = []any{
	(*PostTransactionRequest)(nil),     // 0: ledger.v1.PostTransactionRequest
	(*PostTransactionResponse)(nil),    // 1: ledger.v1.PostTransactionResponse
	(*ReverseTransactionRequest)(nil),  // 2: ledger.v1.ReverseTransactionRequest
	(*ReverseTransactionResponse)(nil), // 3: ledger.v1.ReverseTransactionResponse
	(*GetTransactionRequest)(nil),      // 4: ledger.v1.GetTransactionRequest
	(*GetTransactionResponse)(nil),     // 5: ledger.v1.GetTransactionResponse
	(*GetBalanceRequest)(nil),          // 6: ledger.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),         // 7: ledger.v1.GetBalanceResponse
	(*Entry)(nil),                      // 8: ledger.v1.Entry
	(*LedgerTransaction)(nil),          // 9: ledger.v1.LedgerTransaction
	(*Balance)(nil),                    // 10: ledger.v1.Balance
}
var file_v1_ledger_ledger_service_proto_depIdxs = []int32{
	8,  // 0: ledger.v1.PostTransactionRequest.entries:type_name -> ledger.v1.Entry
	9,  // 1: ledger.v1.PostTransactionResponse.transaction:type_name -> ledger.v1.LedgerTransaction
	9,  // 2: ledger.v1.ReverseTransactionResponse.transaction:type_name -> ledger.v1.LedgerTransaction
	9,  // 3: ledger.v1.GetTransactionResponse.transaction:type_name -> ledger.v1.LedgerTransaction
	10, // 4: ledger.v1.GetBalanceResponse.balance:type_name -> ledger.v1.Balance
	0,  // 5: ledger.v1.LedgerService.PostTransaction:input_type -> ledger.v1.PostTransactionRequest
	2,  // 6: ledger.v1.LedgerService.ReverseTransaction:input_type -> ledger.v1.ReverseTransactionRequest
	4,  // 7: ledger.v1.LedgerService.GetTransaction:input_type -> ledger.v1.GetTransactionRequest
	6,  // 8: ledger.v1.LedgerService.GetBalance:input_type -> ledger.v1.GetBalanceRequest
	1,  // 9: ledger.v1.LedgerService.PostTransaction:output_type -> ledger.v1.PostTransactionResponse
	3,  // 10: ledger.v1.LedgerService.ReverseTransaction:output_type -> ledger.v1.ReverseTransactionResponse
	5,  // 11: ledger.v1.LedgerService.GetTransaction:output_type -> ledger.v1.GetTransactionResponse
	7,  // 12: ledger.v1.LedgerService.GetBalance:output_type -> ledger.v1.GetBalanceResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_ledger_ledger_service_proto_init() }
func file_v1_ledger_ledger_service_proto_init() {
	if File_v1_ledger_ledger_service_proto != nil {
		return
	}
	file_v1_ledger_ledger_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_ledger_ledger_service_proto_rawDesc), len(file_v1_ledger_ledger_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_ledger_ledger_service_proto_goTypes,
		DependencyIndexes: file_v1_ledger_ledger_service_proto_depIdxs,
		MessageInfos:      file_v1_ledger_ledger_service_proto_msgTypes,
	}.Build()
	File_v1_ledger_ledger_service_proto = out.File
	file_v1_ledger_ledger_service_proto_goTypes = nil
	file_v1_ledger_ledger_service_proto_depIdxs = nil
}
