// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/customer/customer_service.proto

package customerv1

import (
	common "github.com/visvesh-ramesh/corebank/v1/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OnboardRequest carries everything needed to open a customer record.
// The oneof details field determines the customer type; exactly one branch
// must be populated. The server sets customer_type on the created Customer
// based on which branch is set.
//
// Validation (enforced in biz layer):
//   - first_name, last_name, email: required
//   - phones: at least one entry; exactly one is_primary = true
//   - addresses: at least one entry; exactly one is_primary = true
//   - details: exactly one branch must be set
type OnboardRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FirstName string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Optional. If blank the server generates "{first_name} {last_name}".
	FullName  string            `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email     string            `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phones    []*common.Phone   `protobuf:"bytes,5,rep,name=phones,proto3" json:"phones,omitempty"`
	Addresses []*common.Address `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*OnboardRequest_Individual
	//	*OnboardRequest_Business
	Details       isOnboardRequest_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardRequest) Reset() {
	*x = OnboardRequest{}
	mi := &file_v1_customer_customer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardRequest) ProtoMessage() {}

func (x *OnboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardRequest.ProtoReflect.Descriptor instead.
func (*OnboardRequest) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_service_proto_rawDescGZIP(), []int{0}
}

func (x *OnboardRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *OnboardRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *OnboardRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *OnboardRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OnboardRequest) GetPhones() []*common.Phone {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *OnboardRequest) GetAddresses() []*common.Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *OnboardRequest) GetDetails() isOnboardRequest_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *OnboardRequest) GetIndividual() *IndividualDetails {
	if x != nil {
		if x, ok := x.Details.(*OnboardRequest_Individual); ok {
			return x.Individual
		}
	}
	return nil
}

func (x *OnboardRequest) GetBusiness() *BusinessDetails {
	if x != nil {
		if x, ok := x.Details.(*OnboardRequest_Business); ok {
			return x.Business
		}
	}
	return nil
}

type isOnboardRequest_Details interface {
	isOnboardRequest_Details()
}

type OnboardRequest_Individual struct {
	Individual *IndividualDetails `protobuf:"bytes,7,opt,name=individual,proto3,oneof"`
}

type OnboardRequest_Business struct {
	Business *BusinessDetails `protobuf:"bytes,8,opt,name=business,proto3,oneof"`
}

func (*OnboardRequest_Individual) isOnboardRequest_Details() {}

func (*OnboardRequest_Business) isOnboardRequest_Details() {}

type OnboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardResponse) Reset() {
	*x = OnboardResponse{}
	mi := &file_v1_customer_customer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardResponse) ProtoMessage() {}

func (x *OnboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardResponse.ProtoReflect.Descriptor instead.
func (*OnboardResponse) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_service_proto_rawDescGZIP(), []int{1}
}

func (x *OnboardResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_v1_customer_customer_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCustomerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_v1_customer_customer_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type UpdateKYCStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewStatus     common.KYCStatus       `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=common.v1.KYCStatus" json:"new_status,omitempty"` // transition validated server-side
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                                  // audit note for the transition
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKYCStatusRequest) Reset() {
	*x = UpdateKYCStatusRequest{}
	mi := &file_v1_customer_customer_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKYCStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKYCStatusRequest) ProtoMessage() {}

func (x *UpdateKYCStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKYCStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateKYCStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateKYCStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateKYCStatusRequest) GetNewStatus() common.KYCStatus {
	if x != nil {
		return x.NewStatus
	}
	return common.KYCStatus(0)
}

func (x *UpdateKYCStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpdateKYCStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKYCStatusResponse) Reset() {
	*x = UpdateKYCStatusResponse{}
	mi := &file_v1_customer_customer_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKYCStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKYCStatusResponse) ProtoMessage() {}

func (x *UpdateKYCStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKYCStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateKYCStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateKYCStatusResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type CloseCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCustomerRequest) Reset() {
	*x = CloseCustomerRequest{}
	mi := &file_v1_customer_customer_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCustomerRequest) ProtoMessage() {}

func (x *CloseCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCustomerRequest.ProtoReflect.Descriptor instead.
func (*CloseCustomerRequest) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_service_proto_rawDescGZIP(), []int{6}
}

func (x *CloseCustomerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CloseCustomerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CloseCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCustomerResponse) Reset() {
	*x = CloseCustomerResponse{}
	mi := &file_v1_customer_customer_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCustomerResponse) ProtoMessage() {}

func (x *CloseCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCustomerResponse.ProtoReflect.Descriptor instead.
func (*CloseCustomerResponse) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_service_proto_rawDescGZIP(), []int{7}
}

func (x *CloseCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type ListCustomersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters. UNSPECIFIED means "all values".
	StatusFilter  common.KYCStatus    `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=common.v1.KYCStatus" json:"status_filter,omitempty"`
	TypeFilter    common.CustomerType `protobuf:"varint,2,opt,name=type_filter,json=typeFilter,proto3,enum=common.v1.CustomerType" json:"type_filter,omitempty"`
	Page          *common.PageRequest `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersRequest) Reset() {
	*x = ListCustomersRequest{}
	mi := &file_v1_customer_customer_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersRequest) ProtoMessage() {}

func (x *ListCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersRequest.ProtoReflect.Descriptor instead.
func (*ListCustomersRequest) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListCustomersRequest) GetStatusFilter() common.KYCStatus {
	if x != nil {
		return x.StatusFilter
	}
	return common.KYCStatus(0)
}

func (x *ListCustomersRequest) GetTypeFilter() common.CustomerType {
	if x != nil {
		return x.TypeFilter
	}
	return common.CustomerType(0)
}

func (x *ListCustomersRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListCustomersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersResponse) Reset() {
	*x = ListCustomersResponse{}
	mi := &file_v1_customer_customer_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersResponse) ProtoMessage() {}

func (x *ListCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersResponse.ProtoReflect.Descriptor instead.
func (*ListCustomersResponse) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListCustomersResponse) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

func (x *ListCustomersResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_v1_customer_customer_service_proto protoreflect.FileDescriptor

const file_v1_customer_customer_service_proto_rawDesc = "" +
	"\n" +
	"\"v1/customer/customer_service.proto\x12\vcustomer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1av1/customer/customer.proto\x1a\x16v1/common/common.proto\x1a\x15v1/common/enums.proto\"\xe4\x02\n" +
	"\x0eOnboardRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12(\n" +
	"\x06phones\x18\x05 \x03(\v2\x10.common.v1.PhoneR\x06phones\x120\n" +
	"\taddresses\x18\x06 \x03(\v2\x12.common.v1.AddressR\taddresses\x12@\n" +
	"\n" +
	"individual\x18\a \x01(\v2\x1e.customer.v1.IndividualDetailsH\x00R\n" +
	"individual\x12:\n" +
	"\bbusiness\x18\b \x01(\v2\x1c.customer.v1.BusinessDetailsH\x00R\bbusinessB\t\n" +
	"\adetails\"D\n" +
	"\x0fOnboardResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\"$\n" +
	"\x12GetCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\x13GetCustomerResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\"u\n" +
	"\x16UpdateKYCStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x123\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x14.common.v1.KYCStatusR\tnewStatus\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"L\n" +
	"\x17UpdateKYCStatusResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\">\n" +
	"\x14CloseCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"J\n" +
	"\x15CloseCustomerResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\"\xb7\x01\n" +
	"\x14ListCustomersRequest\x129\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x14.common.v1.KYCStatusR\fstatusFilter\x128\n" +
	"\vtype_filter\x18\x02 \x01(\x0e2\x17.common.v1.CustomerTypeR\n" +
	"typeFilter\x12*\n" +
	"\x04page\x18\x03 \x01(\v2\x16.common.v1.PageRequestR\x04page\"y\n" +
	"\x15ListCustomersResponse\x123\n" +
	"\tcustomers\x18\x01 \x03(\v2\x15.customer.v1.CustomerR\tcustomers\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page2\xd4\x04\n" +
	"\x0fCustomerService\x12^\n" +
	"\aOnboard\x12\x1b.customer.v1.OnboardRequest\x1a\x1c.customer.v1.OnboardResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/customers\x12l\n" +
	"\vGetCustomer\x12\x1f.customer.v1.GetCustomerRequest\x1a .customer.v1.GetCustomerResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/customers/{id}\x12\x86\x01\n" +
	"\x0fUpdateKYCStatus\x12#.customer.v1.UpdateKYCStatusRequest\x1a$.customer.v1.UpdateKYCStatusResponse\"(\x82\xd3\xe4\x93\x02\":\x01*2\x1d/v1/customers/{id}/kyc-status\x12{\n" +
	"\rCloseCustomer\x12!.customer.v1.CloseCustomerRequest\x1a\".customer.v1.CloseCustomerResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/customers/{id}:close\x12m\n" +
	"\rListCustomers\x12!.customer.v1.ListCustomersRequest\x1a\".customer.v1.ListCustomersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/customersB;Z9github.com/visvesh-ramesh/corebank/v1/customer;customerv1b\x06proto3"

var (
	file_v1_customer_customer_service_proto_rawDescOnce sync.Once
	file_v1_customer_customer_service_proto_rawDescData []byte
)

func file_v1_customer_customer_service_proto_rawDescGZIP() []byte {
	file_v1_customer_customer_service_proto_rawDescOnce.Do(func() {
		file_v1_customer_customer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_customer_customer_service_proto_rawDesc), len(file_v1_customer_customer_service_proto_rawDesc)))
	})
	return file_v1_customer_customer_service_proto_rawDescData
}

var file_v1_customer_customer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_customer_customer_service_proto_goTypes = []any{
	(*OnboardRequest)(nil),          // 0: customer.v1.OnboardRequest
	(*OnboardResponse)(nil),         // 1: customer.v1.OnboardResponse
	(*GetCustomerRequest)(nil),      // 2: customer.v1.GetCustomerRequest
	(*GetCustomerResponse)(nil),     // 3: customer.v1.GetCustomerResponse
	(*UpdateKYCStatusRequest)(nil),  // 4: customer.v1.UpdateKYCStatusRequest
	(*UpdateKYCStatusResponse)(nil), // 5: customer.v1.UpdateKYCStatusResponse
	(*CloseCustomerRequest)(nil),    // 6: customer.v1.CloseCustomerRequest
	(*CloseCustomerResponse)(nil),   // 7: customer.v1.CloseCustomerResponse
	(*ListCustomersRequest)(nil),    // 8: customer.v1.ListCustomersRequest
	(*ListCustomersResponse)(nil),   // 9: customer.v1.ListCustomersResponse
	(*common.Phone)(nil),            // 10: common.v1.Phone
	(*common.Address)(nil),          // 11: common.v1.Address
	(*IndividualDetails)(nil),       // 12: customer.v1.IndividualDetails
	(*BusinessDetails)(nil),         // 13: customer.v1.BusinessDetails
	(*Customer)(nil),                // 14: customer.v1.Customer
	(common.KYCStatus)(0),           // 15: common.v1.KYCStatus
	(common.CustomerType)(0),        // 16: common.v1.CustomerType
	(*common.PageRequest)(nil),      // 17: common.v1.PageRequest
	(*common.PageResponse)(nil),     // 18: common.v1.PageResponse
}
var file_v1_customer_customer_service_proto_depIdxs = []int32{
	10, // 0: customer.v1.OnboardRequest.phones:type_name -> common.v1.Phone
	11, // 1: customer.v1.OnboardRequest.addresses:type_name -> common.v1.Address
	12, // 2: customer.v1.OnboardRequest.individual:type_name -> customer.v1.IndividualDetails
	13, // 3: customer.v1.OnboardRequest.business:type_name -> customer.v1.BusinessDetails
	14, // 4: customer.v1.OnboardResponse.customer:type_name -> customer.v1.Customer
	14, // 5: customer.v1.GetCustomerResponse.customer:type_name -> customer.v1.Customer
	15, // 6: customer.v1.UpdateKYCStatusRequest.new_status:type_name -> common.v1.KYCStatus
	14, // 7: customer.v1.UpdateKYCStatusResponse.customer:type_name -> customer.v1.Customer
	14, // 8: customer.v1.CloseCustomerResponse.customer:type_name -> customer.v1.Customer
	15, // 9: customer.v1.ListCustomersRequest.status_filter:type_name -> common.v1.KYCStatus
	16, // 10: customer.v1.ListCustomersRequest.type_filter:type_name -> common.v1.CustomerType
	17, // 11: customer.v1.ListCustomersRequest.page:type_name -> common.v1.PageRequest
	14, // 12: customer.v1.ListCustomersResponse.customers:type_name -> customer.v1.Customer
	18, // 13: customer.v1.ListCustomersResponse.page:type_name -> common.v1.PageResponse
	0,  // 14: customer.v1.CustomerService.Onboard:input_type -> customer.v1.OnboardRequest
	2,  // 15: customer.v1.CustomerService.GetCustomer:input_type -> customer.v1.GetCustomerRequest
	4,  // 16: customer.v1.CustomerService.UpdateKYCStatus:input_type -> customer.v1.UpdateKYCStatusRequest
	6,  // 17: customer.v1.CustomerService.CloseCustomer:input_type -> customer.v1.CloseCustomerRequest
	8,  // 18: customer.v1.CustomerService.ListCustomers:input_type -> customer.v1.ListCustomersRequest
	1,  // 19: customer.v1.CustomerService.Onboard:output_type -> customer.v1.OnboardResponse
	3,  // 20: customer.v1.CustomerService.GetCustomer:output_type -> customer.v1.GetCustomerResponse
	5,  // 21: customer.v1.CustomerService.UpdateKYCStatus:output_type -> customer.v1.UpdateKYCStatusResponse
	7,  // 22: customer.v1.CustomerService.CloseCustomer:output_type -> customer.v1.CloseCustomerResponse
	9,  // 23: customer.v1.CustomerService.ListCustomers:output_type -> customer.v1.ListCustomersResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_customer_customer_service_proto_init() }
func file_v1_customer_customer_service_proto_init() {
	if File_v1_customer_customer_service_proto != nil {
		return
	}
	file_v1_customer_customer_proto_init()
	file_v1_customer_customer_service_proto_msgTypes[0].OneofWrappers = []any{
		(*OnboardRequest_Individual)(nil),
		(*OnboardRequest_Business)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_customer_customer_service_proto_rawDesc), len(file_v1_customer_customer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_customer_customer_service_proto_goTypes,
		DependencyIndexes: file_v1_customer_customer_service_proto_depIdxs,
		MessageInfos:      file_v1_customer_customer_service_proto_msgTypes,
	}.Build()
	File_v1_customer_customer_service_proto = out.File
	file_v1_customer_customer_service_proto_goTypes = nil
	file_v1_customer_customer_service_proto_depIdxs = nil
}
