// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/customer/customer.proto

package customerv1

import (
	common "github.com/visvesh-ramesh/corebank/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Customer is the core identity record. It owns NO money and NO accounts
// directly — the Account service references a customer_id. Keeping identity
// separate from accounts is a deliberate architectural boundary.
//
// The customer's type-specific information lives in the oneof `details` field:
//   - individual: personal KYC data (date of birth, national ID, etc.)
//   - business:   company registration, authorized representative info
//
// Validation requirements (enforced in biz layer):
//   - phones must have at least one entry; exactly one must be is_primary = true
//   - addresses must have at least one entry; exactly one must be is_primary = true
//   - details must be set (one of individual or business)
type Customer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-generated identifier (auto-increment bigint in PostgreSQL).
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Mirrors which branch of details is set; stored for efficient filtering.
	CustomerType common.CustomerType `protobuf:"varint,2,opt,name=customer_type,json=customerType,proto3,enum=common.v1.CustomerType" json:"customer_type,omitempty"`
	// For INDIVIDUAL: the customer's own name.
	// For BUSINESS: the primary authorized representative's name.
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Optional computed/display name (e.g. "Acme Corp — Jane Doe").
	// If blank on create the server generates it as "{first_name} {last_name}".
	FullName string `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// Primary email address — used for notifications and account recovery.
	// Required on onboarding.
	Email string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	// At least one phone required. Exactly one must carry is_primary = true.
	Phones []*common.Phone `protobuf:"bytes,7,rep,name=phones,proto3" json:"phones,omitempty"`
	// At least one address required. Exactly one must carry is_primary = true.
	Addresses []*common.Address      `protobuf:"bytes,8,rep,name=addresses,proto3" json:"addresses,omitempty"`
	KycStatus common.KYCStatus       `protobuf:"varint,9,opt,name=kyc_status,json=kycStatus,proto3,enum=common.v1.KYCStatus" json:"kyc_status,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Type-specific KYC payload. Exactly one branch must be set; setting neither
	// or both is rejected. The set branch determines customer_type.
	//
	// Types that are valid to be assigned to Details:
	//
	//	*Customer_Individual
	//	*Customer_Business
	Details       isCustomer_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_v1_customer_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Customer) GetCustomerType() common.CustomerType {
	if x != nil {
		return x.CustomerType
	}
	return common.CustomerType(0)
}

func (x *Customer) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Customer) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Customer) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetPhones() []*common.Phone {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *Customer) GetAddresses() []*common.Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Customer) GetKycStatus() common.KYCStatus {
	if x != nil {
		return x.KycStatus
	}
	return common.KYCStatus(0)
}

func (x *Customer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Customer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Customer) GetDetails() isCustomer_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Customer) GetIndividual() *IndividualDetails {
	if x != nil {
		if x, ok := x.Details.(*Customer_Individual); ok {
			return x.Individual
		}
	}
	return nil
}

func (x *Customer) GetBusiness() *BusinessDetails {
	if x != nil {
		if x, ok := x.Details.(*Customer_Business); ok {
			return x.Business
		}
	}
	return nil
}

type isCustomer_Details interface {
	isCustomer_Details()
}

type Customer_Individual struct {
	Individual *IndividualDetails `protobuf:"bytes,12,opt,name=individual,proto3,oneof"`
}

type Customer_Business struct {
	Business *BusinessDetails `protobuf:"bytes,13,opt,name=business,proto3,oneof"`
}

func (*Customer_Individual) isCustomer_Details() {}

func (*Customer_Business) isCustomer_Details() {}

// IndividualDetails holds KYC fields specific to a natural person.
type IndividualDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ISO 8601 date of birth, e.g. "1990-06-15".
	DateOfBirth string `protobuf:"bytes,1,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	// ISO 3166-1 alpha-2 nationality, e.g. "IN".
	Nationality string `protobuf:"bytes,2,opt,name=nationality,proto3" json:"nationality,omitempty"`
	// Government-issued primary ID number (Aadhaar, passport, SSN, etc.).
	NationalId    string `protobuf:"bytes,3,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndividualDetails) Reset() {
	*x = IndividualDetails{}
	mi := &file_v1_customer_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndividualDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndividualDetails) ProtoMessage() {}

func (x *IndividualDetails) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndividualDetails.ProtoReflect.Descriptor instead.
func (*IndividualDetails) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_proto_rawDescGZIP(), []int{1}
}

func (x *IndividualDetails) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *IndividualDetails) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *IndividualDetails) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

// BusinessDetails holds KYC fields specific to a registered business entity.
// The business must supply its own contact information AND the details of the
// authorized representative (proprietor/director) who is accountable for the
// account.
//
// Validation requirements (enforced in biz layer):
//   - company_phones must have at least one entry
//   - registered_addresses must have at least one entry
//   - proprietor must be fully populated
type BusinessDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Legal registered name of the company.
	CompanyName string `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	// Company registration / incorporation number (e.g. CIN in India).
	RegistrationNumber string `protobuf:"bytes,2,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	// Tax identification number (GST, TIN, EIN, etc.).
	TaxId string `protobuf:"bytes,3,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	// Company-level contact phones.
	// At least one required; exactly one must be is_primary = true.
	CompanyPhones []*common.Phone `protobuf:"bytes,4,rep,name=company_phones,json=companyPhones,proto3" json:"company_phones,omitempty"`
	// Company registered and/or correspondence addresses.
	// At least one required; exactly one must be is_primary = true.
	RegisteredAddresses []*common.Address `protobuf:"bytes,5,rep,name=registered_addresses,json=registeredAddresses,proto3" json:"registered_addresses,omitempty"`
	// The authorized representative who is personally accountable.
	Proprietor    *ProprietorInfo `protobuf:"bytes,6,opt,name=proprietor,proto3" json:"proprietor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessDetails) Reset() {
	*x = BusinessDetails{}
	mi := &file_v1_customer_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessDetails) ProtoMessage() {}

func (x *BusinessDetails) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessDetails.ProtoReflect.Descriptor instead.
func (*BusinessDetails) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_proto_rawDescGZIP(), []int{2}
}

func (x *BusinessDetails) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *BusinessDetails) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *BusinessDetails) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *BusinessDetails) GetCompanyPhones() []*common.Phone {
	if x != nil {
		return x.CompanyPhones
	}
	return nil
}

func (x *BusinessDetails) GetRegisteredAddresses() []*common.Address {
	if x != nil {
		return x.RegisteredAddresses
	}
	return nil
}

func (x *BusinessDetails) GetProprietor() *ProprietorInfo {
	if x != nil {
		return x.Proprietor
	}
	return nil
}

// ProprietorInfo identifies the natural person who owns or controls the
// business and is personally responsible for the account relationship.
type ProprietorInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FirstName string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Direct email for the proprietor (may differ from the company email).
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// At least one phone required.
	Phones []*common.Phone `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	// Government-issued primary ID of the proprietor.
	NationalId    string `protobuf:"bytes,5,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProprietorInfo) Reset() {
	*x = ProprietorInfo{}
	mi := &file_v1_customer_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProprietorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProprietorInfo) ProtoMessage() {}

func (x *ProprietorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_customer_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProprietorInfo.ProtoReflect.Descriptor instead.
func (*ProprietorInfo) Descriptor() ([]byte, []int) {
	return file_v1_customer_customer_proto_rawDescGZIP(), []int{3}
}

func (x *ProprietorInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ProprietorInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ProprietorInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProprietorInfo) GetPhones() []*common.Phone {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *ProprietorInfo) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

var File_v1_customer_customer_proto protoreflect.FileDescriptor

const file_v1_customer_customer_proto_rawDesc = "" +
	"\n" +
	"\x1av1/customer/customer.proto\x12\vcustomer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16v1/common/common.proto\x1a\x15v1/common/enums.proto\"\xd7\x04\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12<\n" +
	"\rcustomer_type\x18\x02 \x01(\x0e2\x17.common.v1.CustomerTypeR\fcustomerType\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12(\n" +
	"\x06phones\x18\a \x03(\v2\x10.common.v1.PhoneR\x06phones\x120\n" +
	"\taddresses\x18\b \x03(\v2\x12.common.v1.AddressR\taddresses\x123\n" +
	"\n" +
	"kyc_status\x18\t \x01(\x0e2\x14.common.v1.KYCStatusR\tkycStatus\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12@\n" +
	"\n" +
	"individual\x18\f \x01(\v2\x1e.customer.v1.IndividualDetailsH\x00R\n" +
	"individual\x12:\n" +
	"\bbusiness\x18\r \x01(\v2\x1c.customer.v1.BusinessDetailsH\x00R\bbusinessB\t\n" +
	"\adetails\"z\n" +
	"\x11IndividualDetails\x12\"\n" +
	"\rdate_of_birth\x18\x01 \x01(\tR\vdateOfBirth\x12 \n" +
	"\vnationality\x18\x02 \x01(\tR\vnationality\x12\x1f\n" +
	"\vnational_id\x18\x03 \x01(\tR\n" +
	"nationalId\"\xb9\x02\n" +
	"\x0fBusinessDetails\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\x12/\n" +
	"\x13registration_number\x18\x02 \x01(\tR\x12registrationNumber\x12\x15\n" +
	"\x06tax_id\x18\x03 \x01(\tR\x05taxId\x127\n" +
	"\x0ecompany_phones\x18\x04 \x03(\v2\x10.common.v1.PhoneR\rcompanyPhones\x12E\n" +
	"\x14registered_addresses\x18\x05 \x03(\v2\x12.common.v1.AddressR\x13registeredAddresses\x12;\n" +
	"\n" +
	"proprietor\x18\x06 \x01(\v2\x1b.customer.v1.ProprietorInfoR\n" +
	"proprietor\"\xad\x01\n" +
	"\x0eProprietorInfo\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12(\n" +
	"\x06phones\x18\x04 \x03(\v2\x10.common.v1.PhoneR\x06phones\x12\x1f\n" +
	"\vnational_id\x18\x05 \x01(\tR\n" +
	"nationalIdB;Z9github.com/visvesh-ramesh/corebank/v1/customer;customerv1b\x06proto3"

var (
	file_v1_customer_customer_proto_rawDescOnce sync.Once
	file_v1_customer_customer_proto_rawDescData []byte
)

func file_v1_customer_customer_proto_rawDescGZIP() []byte {
	file_v1_customer_customer_proto_rawDescOnce.Do(func() {
		file_v1_customer_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_customer_customer_proto_rawDesc), len(file_v1_customer_customer_proto_rawDesc)))
	})
	return file_v1_customer_customer_proto_rawDescData
}

var file_v1_customer_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_customer_customer_proto_goTypes = []any{
	(*Customer)(nil),              // 0: customer.v1.Customer
	(*IndividualDetails)(nil),     // 1: customer.v1.IndividualDetails
	(*BusinessDetails)(nil),       // 2: customer.v1.BusinessDetails
	(*ProprietorInfo)(nil),        // 3: customer.v1.ProprietorInfo
	(common.CustomerType)(0),      // 4: common.v1.CustomerType
	(*common.Phone)(nil),          // 5: common.v1.Phone
	(*common.Address)(nil),        // 6: common.v1.Address
	(common.KYCStatus)(0),         // 7: common.v1.KYCStatus
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_v1_customer_customer_proto_depIdxs = []int32{
	4,  // 0: customer.v1.Customer.customer_type:type_name -> common.v1.CustomerType
	5,  // 1: customer.v1.Customer.phones:type_name -> common.v1.Phone
	6,  // 2: customer.v1.Customer.addresses:type_name -> common.v1.Address
	7,  // 3: customer.v1.Customer.kyc_status:type_name -> common.v1.KYCStatus
	8,  // 4: customer.v1.Customer.created_at:type_name -> google.protobuf.Timestamp
	8,  // 5: customer.v1.Customer.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: customer.v1.Customer.individual:type_name -> customer.v1.IndividualDetails
	2,  // 7: customer.v1.Customer.business:type_name -> customer.v1.BusinessDetails
	5,  // 8: customer.v1.BusinessDetails.company_phones:type_name -> common.v1.Phone
	6,  // 9: customer.v1.BusinessDetails.registered_addresses:type_name -> common.v1.Address
	3,  // 10: customer.v1.BusinessDetails.proprietor:type_name -> customer.v1.ProprietorInfo
	5,  // 11: customer.v1.ProprietorInfo.phones:type_name -> common.v1.Phone
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_customer_customer_proto_init() }
func file_v1_customer_customer_proto_init() {
	if File_v1_customer_customer_proto != nil {
		return
	}
	file_v1_customer_customer_proto_msgTypes[0].OneofWrappers = []any{
		(*Customer_Individual)(nil),
		(*Customer_Business)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_customer_customer_proto_rawDesc), len(file_v1_customer_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_customer_customer_proto_goTypes,
		DependencyIndexes: file_v1_customer_customer_proto_depIdxs,
		MessageInfos:      file_v1_customer_customer_proto_msgTypes,
	}.Build()
	File_v1_customer_customer_proto = out.File
	file_v1_customer_customer_proto_goTypes = nil
	file_v1_customer_customer_proto_depIdxs = nil
}
