// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/customer/customer_service.proto

package customerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomerService_Onboard_FullMethodName         = "/customer.v1.CustomerService/Onboard"
	CustomerService_GetCustomer_FullMethodName     = "/customer.v1.CustomerService/GetCustomer"
	CustomerService_UpdateKYCStatus_FullMethodName = "/customer.v1.CustomerService/UpdateKYCStatus"
	CustomerService_CloseCustomer_FullMethodName   = "/customer.v1.CustomerService/CloseCustomer"
	CustomerService_ListCustomers_FullMethodName   = "/customer.v1.CustomerService/ListCustomers"
)

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CustomerService manages the customer identity lifecycle.
//
// Every RPC carries a google.api.http annotation so buf generate emits both
// a gRPC server (used internally, service-to-service) and a REST/JSON gateway
// (exposed at the edge) from this single contract.
type CustomerServiceClient interface {
	// Onboard creates a new customer in PENDING status and kicks off KYC.
	// The request must include type-specific details via the details oneof;
	// omitting it or setting both branches is rejected (VALIDATION_FAILED).
	// At least one phone and one address are required.
	Onboard(ctx context.Context, in *OnboardRequest, opts ...grpc.CallOption) (*OnboardResponse, error)
	GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error)
	// UpdateKYCStatus transitions a customer through the KYC lifecycle.
	// The requested transition is validated against the state machine;
	// illegal moves (e.g. CLOSED → ACTIVE) are rejected (ILLEGAL_TRANSITION).
	UpdateKYCStatus(ctx context.Context, in *UpdateKYCStatusRequest, opts ...grpc.CallOption) (*UpdateKYCStatusResponse, error)
	// CloseCustomer moves a customer to the terminal CLOSED status.
	// No hard delete — records are retained for regulatory compliance.
	CloseCustomer(ctx context.Context, in *CloseCustomerRequest, opts ...grpc.CallOption) (*CloseCustomerResponse, error)
	// ListCustomers returns a paginated list, optionally filtered by KYC status
	// and/or customer type.
	ListCustomers(ctx context.Context, in *ListCustomersRequest, opts ...grpc.CallOption) (*ListCustomersResponse, error)
}

type customerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerServiceClient(cc grpc.ClientConnInterface) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) Onboard(ctx context.Context, in *OnboardRequest, opts ...grpc.CallOption) (*OnboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnboardResponse)
	err := c.cc.Invoke(ctx, CustomerService_Onboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerResponse)
	err := c.cc.Invoke(ctx, CustomerService_GetCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) UpdateKYCStatus(ctx context.Context, in *UpdateKYCStatusRequest, opts ...grpc.CallOption) (*UpdateKYCStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateKYCStatusResponse)
	err := c.cc.Invoke(ctx, CustomerService_UpdateKYCStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) CloseCustomer(ctx context.Context, in *CloseCustomerRequest, opts ...grpc.CallOption) (*CloseCustomerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseCustomerResponse)
	err := c.cc.Invoke(ctx, CustomerService_CloseCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) ListCustomers(ctx context.Context, in *ListCustomersRequest, opts ...grpc.CallOption) (*ListCustomersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCustomersResponse)
	err := c.cc.Invoke(ctx, CustomerService_ListCustomers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
// All implementations should embed UnimplementedCustomerServiceServer
// for forward compatibility.
//
// CustomerService manages the customer identity lifecycle.
//
// Every RPC carries a google.api.http annotation so buf generate emits both
// a gRPC server (used internally, service-to-service) and a REST/JSON gateway
// (exposed at the edge) from this single contract.
type CustomerServiceServer interface {
	// Onboard creates a new customer in PENDING status and kicks off KYC.
	// The request must include type-specific details via the details oneof;
	// omitting it or setting both branches is rejected (VALIDATION_FAILED).
	// At least one phone and one address are required.
	Onboard(context.Context, *OnboardRequest) (*OnboardResponse, error)
	GetCustomer(context.Context, *GetCustomerRequest) (*GetCustomerResponse, error)
	// UpdateKYCStatus transitions a customer through the KYC lifecycle.
	// The requested transition is validated against the state machine;
	// illegal moves (e.g. CLOSED → ACTIVE) are rejected (ILLEGAL_TRANSITION).
	UpdateKYCStatus(context.Context, *UpdateKYCStatusRequest) (*UpdateKYCStatusResponse, error)
	// CloseCustomer moves a customer to the terminal CLOSED status.
	// No hard delete — records are retained for regulatory compliance.
	CloseCustomer(context.Context, *CloseCustomerRequest) (*CloseCustomerResponse, error)
	// ListCustomers returns a paginated list, optionally filtered by KYC status
	// and/or customer type.
	ListCustomers(context.Context, *ListCustomersRequest) (*ListCustomersResponse, error)
}

// UnimplementedCustomerServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerServiceServer struct{}

func (UnimplementedCustomerServiceServer) Onboard(context.Context, *OnboardRequest) (*OnboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Onboard not implemented")
}
func (UnimplementedCustomerServiceServer) GetCustomer(context.Context, *GetCustomerRequest) (*GetCustomerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomer not implemented")
}
func (UnimplementedCustomerServiceServer) UpdateKYCStatus(context.Context, *UpdateKYCStatusRequest) (*UpdateKYCStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKYCStatus not implemented")
}
func (UnimplementedCustomerServiceServer) CloseCustomer(context.Context, *CloseCustomerRequest) (*CloseCustomerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseCustomer not implemented")
}
func (UnimplementedCustomerServiceServer) ListCustomers(context.Context, *ListCustomersRequest) (*ListCustomersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCustomers not implemented")
}
func (UnimplementedCustomerServiceServer) testEmbeddedByValue() {}

// UnsafeCustomerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerServiceServer will
// result in compilation errors.
type UnsafeCustomerServiceServer interface {
	mustEmbedUnimplementedCustomerServiceServer()
}

func RegisterCustomerServiceServer(s grpc.ServiceRegistrar, srv CustomerServiceServer) {
	// If the following call panics, it indicates UnimplementedCustomerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomerService_ServiceDesc, srv)
}

func _CustomerService_Onboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).Onboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_Onboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).Onboard(ctx, req.(*OnboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomer(ctx, req.(*GetCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_UpdateKYCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKYCStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).UpdateKYCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_UpdateKYCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).UpdateKYCStatus(ctx, req.(*UpdateKYCStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_CloseCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CloseCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_CloseCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CloseCustomer(ctx, req.(*CloseCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_ListCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCustomersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).ListCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_ListCustomers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).ListCustomers(ctx, req.(*ListCustomersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerService_ServiceDesc is the grpc.ServiceDesc for CustomerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer.v1.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Onboard",
			Handler:    _CustomerService_Onboard_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _CustomerService_GetCustomer_Handler,
		},
		{
			MethodName: "UpdateKYCStatus",
			Handler:    _CustomerService_UpdateKYCStatus_Handler,
		},
		{
			MethodName: "CloseCustomer",
			Handler:    _CustomerService_CloseCustomer_Handler,
		},
		{
			MethodName: "ListCustomers",
			Handler:    _CustomerService_ListCustomers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/customer/customer_service.proto",
}
