// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/customer/customer_service.proto

package customerv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCustomerServiceCloseCustomer = "/customer.v1.CustomerService/CloseCustomer"
const OperationCustomerServiceGetCustomer = "/customer.v1.CustomerService/GetCustomer"
const OperationCustomerServiceListCustomers = "/customer.v1.CustomerService/ListCustomers"
const OperationCustomerServiceOnboard = "/customer.v1.CustomerService/Onboard"
const OperationCustomerServiceUpdateKYCStatus = "/customer.v1.CustomerService/UpdateKYCStatus"

type CustomerServiceHTTPServer interface {
	// CloseCustomer CloseCustomer moves a customer to the terminal CLOSED status.
	// No hard delete — records are retained for regulatory compliance.
	CloseCustomer(context.Context, *CloseCustomerRequest) (*CloseCustomerResponse, error)
	GetCustomer(context.Context, *GetCustomerRequest) (*GetCustomerResponse, error)
	// ListCustomers ListCustomers returns a paginated list, optionally filtered by KYC status
	// and/or customer type.
	ListCustomers(context.Context, *ListCustomersRequest) (*ListCustomersResponse, error)
	// Onboard Onboard creates a new customer in PENDING status and kicks off KYC.
	// The request must include type-specific details via the details oneof;
	// omitting it or setting both branches is rejected (VALIDATION_FAILED).
	// At least one phone and one address are required.
	Onboard(context.Context, *OnboardRequest) (*OnboardResponse, error)
	// UpdateKYCStatus UpdateKYCStatus transitions a customer through the KYC lifecycle.
	// The requested transition is validated against the state machine;
	// illegal moves (e.g. CLOSED → ACTIVE) are rejected (ILLEGAL_TRANSITION).
	UpdateKYCStatus(context.Context, *UpdateKYCStatusRequest) (*UpdateKYCStatusResponse, error)
}

func RegisterCustomerServiceHTTPServer(s *http.Server, srv CustomerServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/customers", _CustomerService_Onboard0_HTTP_Handler(srv))
	r.GET("/v1/customers/{id}", _CustomerService_GetCustomer0_HTTP_Handler(srv))
	r.PATCH("/v1/customers/{id}/kyc-status", _CustomerService_UpdateKYCStatus0_HTTP_Handler(srv))
	r.POST("/v1/customers/{id}:close", _CustomerService_CloseCustomer0_HTTP_Handler(srv))
	r.GET("/v1/customers", _CustomerService_ListCustomers0_HTTP_Handler(srv))
}

func _CustomerService_Onboard0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OnboardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceOnboard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Onboard(ctx, req.(*OnboardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OnboardResponse)
		return ctx.Result(200, reply)
	}
}

func _CustomerService_GetCustomer0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCustomerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceGetCustomer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCustomer(ctx, req.(*GetCustomerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCustomerResponse)
		return ctx.Result(200, reply)
	}
}

func _CustomerService_UpdateKYCStatus0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateKYCStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceUpdateKYCStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateKYCStatus(ctx, req.(*UpdateKYCStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateKYCStatusResponse)
		return ctx.Result(200, reply)
	}
}

func _CustomerService_CloseCustomer0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CloseCustomerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceCloseCustomer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CloseCustomer(ctx, req.(*CloseCustomerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CloseCustomerResponse)
		return ctx.Result(200, reply)
	}
}

func _CustomerService_ListCustomers0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCustomersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceListCustomers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCustomers(ctx, req.(*ListCustomersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCustomersResponse)
		return ctx.Result(200, reply)
	}
}

type CustomerServiceHTTPClient interface {
	// CloseCustomer CloseCustomer moves a customer to the terminal CLOSED status.
	// No hard delete — records are retained for regulatory compliance.
	CloseCustomer(ctx context.Context, req *CloseCustomerRequest, opts ...http.CallOption) (rsp *CloseCustomerResponse, err error)
	GetCustomer(ctx context.Context, req *GetCustomerRequest, opts ...http.CallOption) (rsp *GetCustomerResponse, err error)
	// ListCustomers ListCustomers returns a paginated list, optionally filtered by KYC status
	// and/or customer type.
	ListCustomers(ctx context.Context, req *ListCustomersRequest, opts ...http.CallOption) (rsp *ListCustomersResponse, err error)
	// Onboard Onboard creates a new customer in PENDING status and kicks off KYC.
	// The request must include type-specific details via the details oneof;
	// omitting it or setting both branches is rejected (VALIDATION_FAILED).
	// At least one phone and one address are required.
	Onboard(ctx context.Context, req *OnboardRequest, opts ...http.CallOption) (rsp *OnboardResponse, err error)
	// UpdateKYCStatus UpdateKYCStatus transitions a customer through the KYC lifecycle.
	// The requested transition is validated against the state machine;
	// illegal moves (e.g. CLOSED → ACTIVE) are rejected (ILLEGAL_TRANSITION).
	UpdateKYCStatus(ctx context.Context, req *UpdateKYCStatusRequest, opts ...http.CallOption) (rsp *UpdateKYCStatusResponse, err error)
}

type CustomerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCustomerServiceHTTPClient(client *http.Client) CustomerServiceHTTPClient {
	return &CustomerServiceHTTPClientImpl{client}
}

// CloseCustomer CloseCustomer moves a customer to the terminal CLOSED status.
// No hard delete — records are retained for regulatory compliance.
func (c *CustomerServiceHTTPClientImpl) CloseCustomer(ctx context.Context, in *CloseCustomerRequest, opts ...http.CallOption) (*CloseCustomerResponse, error) {
	var out CloseCustomerResponse
	pattern := "/v1/customers/{id}:close"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCustomerServiceCloseCustomer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CustomerServiceHTTPClientImpl) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...http.CallOption) (*GetCustomerResponse, error) {
	var out GetCustomerResponse
	pattern := "/v1/customers/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCustomerServiceGetCustomer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCustomers ListCustomers returns a paginated list, optionally filtered by KYC status
// and/or customer type.
func (c *CustomerServiceHTTPClientImpl) ListCustomers(ctx context.Context, in *ListCustomersRequest, opts ...http.CallOption) (*ListCustomersResponse, error) {
	var out ListCustomersResponse
	pattern := "/v1/customers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCustomerServiceListCustomers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Onboard Onboard creates a new customer in PENDING status and kicks off KYC.
// The request must include type-specific details via the details oneof;
// omitting it or setting both branches is rejected (VALIDATION_FAILED).
// At least one phone and one address are required.
func (c *CustomerServiceHTTPClientImpl) Onboard(ctx context.Context, in *OnboardRequest, opts ...http.CallOption) (*OnboardResponse, error) {
	var out OnboardResponse
	pattern := "/v1/customers"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCustomerServiceOnboard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateKYCStatus UpdateKYCStatus transitions a customer through the KYC lifecycle.
// The requested transition is validated against the state machine;
// illegal moves (e.g. CLOSED → ACTIVE) are rejected (ILLEGAL_TRANSITION).
func (c *CustomerServiceHTTPClientImpl) UpdateKYCStatus(ctx context.Context, in *UpdateKYCStatusRequest, opts ...http.CallOption) (*UpdateKYCStatusResponse, error) {
	var out UpdateKYCStatusResponse
	pattern := "/v1/customers/{id}/kyc-status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCustomerServiceUpdateKYCStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
